// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cmd_device.proto

// +build !nodev

package aranyagopb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DeviceMetric_ReportMethod int32

const (
	// Report device metrics when collecting node metrics
	REPORT_WITH_NODE_METRICS DeviceMetric_ReportMethod = 0
	// Report device metrics along with arhat client
	REPORT_WITH_ARHAT_CONNECTIVITY DeviceMetric_ReportMethod = 1
	// Create a standalone client for metrics uploading
	REPORT_WITH_STANDALONE_CLIENT DeviceMetric_ReportMethod = 2
)

var DeviceMetric_ReportMethod_name = map[int32]string{
	0: "REPORT_WITH_NODE_METRICS",
	1: "REPORT_WITH_ARHAT_CONNECTIVITY",
	2: "REPORT_WITH_STANDALONE_CLIENT",
}

var DeviceMetric_ReportMethod_value = map[string]int32{
	"REPORT_WITH_NODE_METRICS":       0,
	"REPORT_WITH_ARHAT_CONNECTIVITY": 1,
	"REPORT_WITH_STANDALONE_CLIENT":  2,
}

func (DeviceMetric_ReportMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9e38e886ce453fd3, []int{1, 0}
}

type DeviceMetric_ValueType int32

const (
	METRICS_VALUE_TYPE_UNTYPED DeviceMetric_ValueType = 0
	METRICS_VALUE_TYPE_COUNTER DeviceMetric_ValueType = 1
	METRICS_VALUE_TYPE_GAUGE   DeviceMetric_ValueType = 2
)

var DeviceMetric_ValueType_name = map[int32]string{
	0: "METRICS_VALUE_TYPE_UNTYPED",
	1: "METRICS_VALUE_TYPE_COUNTER",
	2: "METRICS_VALUE_TYPE_GAUGE",
}

var DeviceMetric_ValueType_value = map[string]int32{
	"METRICS_VALUE_TYPE_UNTYPED": 0,
	"METRICS_VALUE_TYPE_COUNTER": 1,
	"METRICS_VALUE_TYPE_GAUGE":   2,
}

func (DeviceMetric_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9e38e886ce453fd3, []int{1, 1}
}

type DeviceOperation struct {
	// (required) identifier of this operation
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// (optional) params usd for device connectivity when executing this
	// operation
	Params map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *DeviceOperation) Reset()      { *m = DeviceOperation{} }
func (*DeviceOperation) ProtoMessage() {}
func (*DeviceOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e38e886ce453fd3, []int{0}
}
func (m *DeviceOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceOperation.Merge(m, src)
}
func (m *DeviceOperation) XXX_Size() int {
	return m.Size()
}
func (m *DeviceOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceOperation.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceOperation proto.InternalMessageInfo

func (m *DeviceOperation) GetOperationId() string {
	if m != nil {
		return m.OperationId
	}
	return ""
}

func (m *DeviceOperation) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type DeviceMetric struct {
	// Name of this metric
	Name         string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReportMethod DeviceMetric_ReportMethod `protobuf:"varint,2,opt,name=report_method,json=reportMethod,proto3,enum=aranya.DeviceMetric_ReportMethod" json:"report_method,omitempty"`
	ValueType    DeviceMetric_ValueType    `protobuf:"varint,3,opt,name=value_type,json=valueType,proto3,enum=aranya.DeviceMetric_ValueType" json:"value_type,omitempty"`
	// (required) params for device connector to retrieve metrics
	DeviceParams map[string]string `protobuf:"bytes,4,rep,name=device_params,json=deviceParams,proto3" json:"device_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Hex encoded hash of the metrics reporter
	ReporterHashHex string `protobuf:"bytes,5,opt,name=reporter_hash_hex,json=reporterHashHex,proto3" json:"reporter_hash_hex,omitempty"`
	// (optional) params for metrics_reporter to upload metrics
	ReporterParams map[string]string `protobuf:"bytes,6,rep,name=reporter_params,json=reporterParams,proto3" json:"reporter_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *DeviceMetric) Reset()      { *m = DeviceMetric{} }
func (*DeviceMetric) ProtoMessage() {}
func (*DeviceMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e38e886ce453fd3, []int{1}
}
func (m *DeviceMetric) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceMetric.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceMetric.Merge(m, src)
}
func (m *DeviceMetric) XXX_Size() int {
	return m.Size()
}
func (m *DeviceMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceMetric.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceMetric proto.InternalMessageInfo

func (m *DeviceMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceMetric) GetReportMethod() DeviceMetric_ReportMethod {
	if m != nil {
		return m.ReportMethod
	}
	return REPORT_WITH_NODE_METRICS
}

func (m *DeviceMetric) GetValueType() DeviceMetric_ValueType {
	if m != nil {
		return m.ValueType
	}
	return METRICS_VALUE_TYPE_UNTYPED
}

func (m *DeviceMetric) GetDeviceParams() map[string]string {
	if m != nil {
		return m.DeviceParams
	}
	return nil
}

func (m *DeviceMetric) GetReporterHashHex() string {
	if m != nil {
		return m.ReporterHashHex
	}
	return ""
}

func (m *DeviceMetric) GetReporterParams() map[string]string {
	if m != nil {
		return m.ReporterParams
	}
	return nil
}

type DeviceEnsureCmd struct {
	Kind DeviceType `protobuf:"varint,1,opt,name=kind,proto3,enum=aranya.DeviceType" json:"kind,omitempty"`
	// (required) Hex encoded hash of the connector of this device
	ConnectorHashHex string `protobuf:"bytes,2,opt,name=connector_hash_hex,json=connectorHashHex,proto3" json:"connector_hash_hex,omitempty"`
	// (required) Connector defines how to connect to the device, operations operate
	// upon this connector
	Connector *Connectivity `protobuf:"bytes,3,opt,name=connector,proto3" json:"connector,omitempty"`
	// (optional) User defined device operations
	Operations []*DeviceOperation `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	// (optional) User defined device metrics
	Metrics []*DeviceMetric `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (m *DeviceEnsureCmd) Reset()      { *m = DeviceEnsureCmd{} }
func (*DeviceEnsureCmd) ProtoMessage() {}
func (*DeviceEnsureCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e38e886ce453fd3, []int{2}
}
func (m *DeviceEnsureCmd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceEnsureCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceEnsureCmd.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceEnsureCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEnsureCmd.Merge(m, src)
}
func (m *DeviceEnsureCmd) XXX_Size() int {
	return m.Size()
}
func (m *DeviceEnsureCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEnsureCmd.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEnsureCmd proto.InternalMessageInfo

func (m *DeviceEnsureCmd) GetKind() DeviceType {
	if m != nil {
		return m.Kind
	}
	return DEVICE_TYPE_UNSPECIFIED
}

func (m *DeviceEnsureCmd) GetConnectorHashHex() string {
	if m != nil {
		return m.ConnectorHashHex
	}
	return ""
}

func (m *DeviceEnsureCmd) GetConnector() *Connectivity {
	if m != nil {
		return m.Connector
	}
	return nil
}

func (m *DeviceEnsureCmd) GetOperations() []*DeviceOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *DeviceEnsureCmd) GetMetrics() []*DeviceMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type DeviceListCmd struct {
	Kind DeviceType `protobuf:"varint,1,opt,name=kind,proto3,enum=aranya.DeviceType" json:"kind,omitempty"`
}

func (m *DeviceListCmd) Reset()      { *m = DeviceListCmd{} }
func (*DeviceListCmd) ProtoMessage() {}
func (*DeviceListCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e38e886ce453fd3, []int{3}
}
func (m *DeviceListCmd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceListCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceListCmd.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceListCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceListCmd.Merge(m, src)
}
func (m *DeviceListCmd) XXX_Size() int {
	return m.Size()
}
func (m *DeviceListCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceListCmd.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceListCmd proto.InternalMessageInfo

func (m *DeviceListCmd) GetKind() DeviceType {
	if m != nil {
		return m.Kind
	}
	return DEVICE_TYPE_UNSPECIFIED
}

type DeviceDeleteCmd struct {
	// delete normal devices
	DeviceIds []string `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	// delete metrics reporters
	MetricsReporterHashHexes []string `protobuf:"bytes,2,rep,name=metrics_reporter_hash_hexes,json=metricsReporterHashHexes,proto3" json:"metrics_reporter_hash_hexes,omitempty"`
}

func (m *DeviceDeleteCmd) Reset()      { *m = DeviceDeleteCmd{} }
func (*DeviceDeleteCmd) ProtoMessage() {}
func (*DeviceDeleteCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e38e886ce453fd3, []int{4}
}
func (m *DeviceDeleteCmd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceDeleteCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceDeleteCmd.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceDeleteCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDeleteCmd.Merge(m, src)
}
func (m *DeviceDeleteCmd) XXX_Size() int {
	return m.Size()
}
func (m *DeviceDeleteCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDeleteCmd.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDeleteCmd proto.InternalMessageInfo

func (m *DeviceDeleteCmd) GetDeviceIds() []string {
	if m != nil {
		return m.DeviceIds
	}
	return nil
}

func (m *DeviceDeleteCmd) GetMetricsReporterHashHexes() []string {
	if m != nil {
		return m.MetricsReporterHashHexes
	}
	return nil
}

func init() {
	proto.RegisterEnum("aranya.DeviceMetric_ReportMethod", DeviceMetric_ReportMethod_name, DeviceMetric_ReportMethod_value)
	proto.RegisterEnum("aranya.DeviceMetric_ValueType", DeviceMetric_ValueType_name, DeviceMetric_ValueType_value)
	proto.RegisterType((*DeviceOperation)(nil), "aranya.DeviceOperation")
	proto.RegisterMapType((map[string]string)(nil), "aranya.DeviceOperation.ParamsEntry")
	proto.RegisterType((*DeviceMetric)(nil), "aranya.DeviceMetric")
	proto.RegisterMapType((map[string]string)(nil), "aranya.DeviceMetric.DeviceParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "aranya.DeviceMetric.ReporterParamsEntry")
	proto.RegisterType((*DeviceEnsureCmd)(nil), "aranya.DeviceEnsureCmd")
	proto.RegisterType((*DeviceListCmd)(nil), "aranya.DeviceListCmd")
	proto.RegisterType((*DeviceDeleteCmd)(nil), "aranya.DeviceDeleteCmd")
}

func init() { proto.RegisterFile("cmd_device.proto", fileDescriptor_9e38e886ce453fd3) }

var fileDescriptor_9e38e886ce453fd3 = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xda, 0x4c,
	0x14, 0xb5, 0x21, 0xf0, 0x89, 0x0b, 0x49, 0x9c, 0xf9, 0x22, 0xd5, 0xa2, 0xcd, 0x28, 0x50, 0x29,
	0x42, 0x55, 0x4b, 0x25, 0xba, 0x48, 0x7f, 0x14, 0x55, 0x14, 0xdc, 0x80, 0x4a, 0x4c, 0x3a, 0x31,
	0x89, 0xd2, 0xcd, 0xc8, 0xc1, 0xa3, 0x62, 0x25, 0xd8, 0xc8, 0x76, 0x50, 0xd8, 0x75, 0xd1, 0x07,
	0xe8, 0x63, 0x74, 0xd1, 0x07, 0xe9, 0x32, 0xcb, 0x74, 0xd7, 0x90, 0x4d, 0x97, 0x79, 0x84, 0x8a,
	0x19, 0x9b, 0x9a, 0x86, 0x54, 0xca, 0xca, 0x33, 0xe7, 0x9e, 0xb9, 0x67, 0x7c, 0xee, 0xbd, 0x03,
	0x4a, 0xb7, 0x6f, 0x51, 0x8b, 0x0d, 0xed, 0x2e, 0x2b, 0x0f, 0x3c, 0x37, 0x70, 0x51, 0xda, 0xf4,
	0x4c, 0x67, 0x64, 0xe6, 0x73, 0x71, 0x34, 0x8f, 0xba, 0xae, 0xe3, 0xb0, 0x6e, 0x60, 0x0f, 0xed,
	0x60, 0x24, 0xb0, 0xe2, 0x37, 0x19, 0x96, 0xeb, 0x9c, 0xd4, 0x1e, 0x30, 0xcf, 0x0c, 0x6c, 0xd7,
	0x41, 0x05, 0xc8, 0xb9, 0xd1, 0x86, 0xda, 0x96, 0x2a, 0xaf, 0xcb, 0xa5, 0x0c, 0xc9, 0x4e, 0xb1,
	0xa6, 0x85, 0x5e, 0x41, 0x7a, 0x60, 0x7a, 0x66, 0xdf, 0x57, 0x13, 0xeb, 0xc9, 0x52, 0xb6, 0xf2,
	0xb0, 0x2c, 0x14, 0xcb, 0x7f, 0xe5, 0x2a, 0xef, 0x72, 0x96, 0xe6, 0x04, 0xde, 0x88, 0x84, 0x47,
	0xf2, 0x2f, 0x20, 0x1b, 0x83, 0x91, 0x02, 0xc9, 0x63, 0x36, 0x0a, 0x55, 0x26, 0x4b, 0xb4, 0x0a,
	0xa9, 0xa1, 0x79, 0x72, 0xca, 0xd4, 0x04, 0xc7, 0xc4, 0xe6, 0x65, 0xe2, 0xb9, 0x5c, 0xfc, 0x91,
	0x82, 0x9c, 0x90, 0xd8, 0x61, 0x81, 0x67, 0x77, 0x11, 0x82, 0x05, 0xc7, 0xec, 0xb3, 0xf0, 0x34,
	0x5f, 0xa3, 0xb7, 0xb0, 0xe8, 0xb1, 0x81, 0xeb, 0x05, 0xb4, 0xcf, 0x82, 0x9e, 0x6b, 0xf1, 0x34,
	0x4b, 0x95, 0xc2, 0xec, 0x1d, 0x45, 0x82, 0x32, 0xe1, 0xcc, 0x1d, 0x4e, 0x24, 0x39, 0x2f, 0xb6,
	0x43, 0x5b, 0x00, 0x5c, 0x99, 0x06, 0xa3, 0x01, 0x53, 0x93, 0x3c, 0x09, 0x9e, 0x9b, 0x64, 0x7f,
	0x42, 0x33, 0x46, 0x03, 0x46, 0x32, 0xc3, 0x68, 0x89, 0xde, 0xc1, 0xa2, 0xb0, 0x9f, 0x86, 0x56,
	0x2d, 0x70, 0xab, 0x36, 0xe6, 0x66, 0x10, 0x9b, 0xb8, 0x5b, 0x61, 0xed, 0x04, 0x84, 0x1e, 0xc1,
	0x8a, 0xb8, 0x1b, 0xf3, 0x68, 0xcf, 0xf4, 0x7b, 0xb4, 0xc7, 0xce, 0xd4, 0x14, 0xff, 0xe9, 0xe5,
	0x28, 0xd0, 0x30, 0xfd, 0x5e, 0x83, 0x9d, 0xa1, 0xf7, 0x30, 0x85, 0x22, 0xe9, 0x34, 0x97, 0x2e,
	0xfd, 0xc3, 0x01, 0xe6, 0xc5, 0xc5, 0x97, 0xbc, 0x19, 0x30, 0xff, 0x1a, 0x56, 0x6e, 0xdc, 0xf0,
	0x2e, 0x85, 0xcb, 0x57, 0xe1, 0xff, 0x39, 0x3a, 0x77, 0xaa, 0xbd, 0x0f, 0xb9, 0x78, 0xb1, 0xd0,
	0x03, 0x50, 0x89, 0xb6, 0xdb, 0x26, 0x06, 0x3d, 0x68, 0x1a, 0x0d, 0xaa, 0xb7, 0xeb, 0x1a, 0xdd,
	0xd1, 0x0c, 0xd2, 0xac, 0xed, 0x29, 0x12, 0x2a, 0x02, 0x8e, 0x47, 0xab, 0xa4, 0x51, 0x35, 0x68,
	0xad, 0xad, 0xeb, 0x5a, 0xcd, 0x68, 0xee, 0x37, 0x8d, 0x43, 0x45, 0x46, 0x05, 0x58, 0x8b, 0x73,
	0xf6, 0x8c, 0xaa, 0x5e, 0xaf, 0xb6, 0xda, 0xba, 0x46, 0x6b, 0xad, 0xa6, 0xa6, 0x1b, 0x4a, 0xa2,
	0x68, 0x43, 0x66, 0x5a, 0x5c, 0x84, 0x21, 0x1f, 0x0a, 0xd0, 0xfd, 0x6a, 0xab, 0xa3, 0x51, 0xe3,
	0x70, 0x57, 0xa3, 0x1d, 0x7d, 0xf2, 0xa9, 0x2b, 0xd2, 0x2d, 0xf1, 0x5a, 0xbb, 0xa3, 0x1b, 0x1a,
	0x51, 0xe4, 0xc9, 0x8d, 0xe7, 0xc4, 0xb7, 0xab, 0x9d, 0x6d, 0x4d, 0x49, 0x14, 0x3f, 0x27, 0xa2,
	0x51, 0xd4, 0x1c, 0xff, 0xd4, 0x63, 0xb5, 0xbe, 0x85, 0x36, 0x60, 0xe1, 0xd8, 0x76, 0xc4, 0x08,
	0x2e, 0x55, 0xd0, 0x6c, 0xfd, 0x78, 0xc3, 0xf1, 0x38, 0x7a, 0x0c, 0xd1, 0x70, 0xbb, 0xb1, 0xfe,
	0x10, 0x16, 0x2a, 0xd3, 0x48, 0xd4, 0x20, 0x15, 0xc8, 0x4c, 0x31, 0xde, 0xd7, 0xd9, 0xca, 0x6a,
	0x94, 0xba, 0x16, 0x7b, 0x23, 0xc8, 0x1f, 0x1a, 0xda, 0x04, 0x98, 0x3e, 0x00, 0x51, 0x2b, 0xdf,
	0xbb, 0x65, 0xea, 0x49, 0x8c, 0x8a, 0xca, 0xf0, 0x5f, 0x9f, 0x37, 0x9a, 0xaf, 0xa6, 0xf8, 0xa9,
	0xd5, 0x79, 0x5d, 0x48, 0x22, 0x52, 0x71, 0x13, 0x16, 0x45, 0xa0, 0x65, 0xfb, 0xc1, 0x1d, 0x3c,
	0x28, 0xba, 0x91, 0x7d, 0x75, 0x76, 0xc2, 0x02, 0x6e, 0xdf, 0x1a, 0x40, 0x38, 0x82, 0xb6, 0xe5,
	0xab, 0xf2, 0x7a, 0xb2, 0x94, 0x21, 0x19, 0x81, 0x34, 0x2d, 0x1f, 0x6d, 0xc1, 0xfd, 0x50, 0x95,
	0xde, 0x18, 0x2e, 0x26, 0x9e, 0xb6, 0x0c, 0x51, 0x43, 0x0a, 0x99, 0x9d, 0x32, 0xe6, 0xbf, 0x39,
	0x38, 0xbf, 0xc4, 0xd2, 0xc5, 0x25, 0x96, 0xae, 0x2f, 0xb1, 0xfc, 0x69, 0x8c, 0xe5, 0xaf, 0x63,
	0x2c, 0x7f, 0x1f, 0x63, 0xf9, 0x7c, 0x8c, 0xe5, 0x9f, 0x63, 0x2c, 0xff, 0x1a, 0x63, 0xe9, 0x7a,
	0x8c, 0xe5, 0x2f, 0x57, 0x58, 0x3a, 0xbf, 0xc2, 0xd2, 0xc5, 0x15, 0x96, 0x3e, 0x14, 0x4c, 0xaf,
	0x67, 0x06, 0x65, 0x8b, 0x0d, 0x9f, 0x8a, 0x3f, 0x79, 0xc2, 0x5f, 0xe2, 0x70, 0xf3, 0xd1, 0x1d,
	0x1c, 0x1d, 0xa5, 0x39, 0xf2, 0xec, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x48, 0x88, 0x74,
	0xd9, 0x05, 0x00, 0x00,
}

func (x DeviceMetric_ReportMethod) String() string {
	s, ok := DeviceMetric_ReportMethod_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x DeviceMetric_ValueType) String() string {
	s, ok := DeviceMetric_ValueType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *DeviceOperation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeviceOperation)
	if !ok {
		that2, ok := that.(DeviceOperation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.OperationId != that1.OperationId {
		return false
	}
	if len(this.Params) != len(that1.Params) {
		return false
	}
	for i := range this.Params {
		if this.Params[i] != that1.Params[i] {
			return false
		}
	}
	return true
}
func (this *DeviceMetric) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeviceMetric)
	if !ok {
		that2, ok := that.(DeviceMetric)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.ReportMethod != that1.ReportMethod {
		return false
	}
	if this.ValueType != that1.ValueType {
		return false
	}
	if len(this.DeviceParams) != len(that1.DeviceParams) {
		return false
	}
	for i := range this.DeviceParams {
		if this.DeviceParams[i] != that1.DeviceParams[i] {
			return false
		}
	}
	if this.ReporterHashHex != that1.ReporterHashHex {
		return false
	}
	if len(this.ReporterParams) != len(that1.ReporterParams) {
		return false
	}
	for i := range this.ReporterParams {
		if this.ReporterParams[i] != that1.ReporterParams[i] {
			return false
		}
	}
	return true
}
func (this *DeviceEnsureCmd) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeviceEnsureCmd)
	if !ok {
		that2, ok := that.(DeviceEnsureCmd)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Kind != that1.Kind {
		return false
	}
	if this.ConnectorHashHex != that1.ConnectorHashHex {
		return false
	}
	if !this.Connector.Equal(that1.Connector) {
		return false
	}
	if len(this.Operations) != len(that1.Operations) {
		return false
	}
	for i := range this.Operations {
		if !this.Operations[i].Equal(that1.Operations[i]) {
			return false
		}
	}
	if len(this.Metrics) != len(that1.Metrics) {
		return false
	}
	for i := range this.Metrics {
		if !this.Metrics[i].Equal(that1.Metrics[i]) {
			return false
		}
	}
	return true
}
func (this *DeviceListCmd) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeviceListCmd)
	if !ok {
		that2, ok := that.(DeviceListCmd)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Kind != that1.Kind {
		return false
	}
	return true
}
func (this *DeviceDeleteCmd) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeviceDeleteCmd)
	if !ok {
		that2, ok := that.(DeviceDeleteCmd)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.DeviceIds) != len(that1.DeviceIds) {
		return false
	}
	for i := range this.DeviceIds {
		if this.DeviceIds[i] != that1.DeviceIds[i] {
			return false
		}
	}
	if len(this.MetricsReporterHashHexes) != len(that1.MetricsReporterHashHexes) {
		return false
	}
	for i := range this.MetricsReporterHashHexes {
		if this.MetricsReporterHashHexes[i] != that1.MetricsReporterHashHexes[i] {
			return false
		}
	}
	return true
}
func (this *DeviceOperation) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&aranyagopb.DeviceOperation{")
	s = append(s, "OperationId: "+fmt.Sprintf("%#v", this.OperationId)+",\n")
	keysForParams := make([]string, 0, len(this.Params))
	for k, _ := range this.Params {
		keysForParams = append(keysForParams, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForParams)
	mapStringForParams := "map[string]string{"
	for _, k := range keysForParams {
		mapStringForParams += fmt.Sprintf("%#v: %#v,", k, this.Params[k])
	}
	mapStringForParams += "}"
	if this.Params != nil {
		s = append(s, "Params: "+mapStringForParams+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeviceMetric) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&aranyagopb.DeviceMetric{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "ReportMethod: "+fmt.Sprintf("%#v", this.ReportMethod)+",\n")
	s = append(s, "ValueType: "+fmt.Sprintf("%#v", this.ValueType)+",\n")
	keysForDeviceParams := make([]string, 0, len(this.DeviceParams))
	for k, _ := range this.DeviceParams {
		keysForDeviceParams = append(keysForDeviceParams, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForDeviceParams)
	mapStringForDeviceParams := "map[string]string{"
	for _, k := range keysForDeviceParams {
		mapStringForDeviceParams += fmt.Sprintf("%#v: %#v,", k, this.DeviceParams[k])
	}
	mapStringForDeviceParams += "}"
	if this.DeviceParams != nil {
		s = append(s, "DeviceParams: "+mapStringForDeviceParams+",\n")
	}
	s = append(s, "ReporterHashHex: "+fmt.Sprintf("%#v", this.ReporterHashHex)+",\n")
	keysForReporterParams := make([]string, 0, len(this.ReporterParams))
	for k, _ := range this.ReporterParams {
		keysForReporterParams = append(keysForReporterParams, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForReporterParams)
	mapStringForReporterParams := "map[string]string{"
	for _, k := range keysForReporterParams {
		mapStringForReporterParams += fmt.Sprintf("%#v: %#v,", k, this.ReporterParams[k])
	}
	mapStringForReporterParams += "}"
	if this.ReporterParams != nil {
		s = append(s, "ReporterParams: "+mapStringForReporterParams+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeviceEnsureCmd) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&aranyagopb.DeviceEnsureCmd{")
	s = append(s, "Kind: "+fmt.Sprintf("%#v", this.Kind)+",\n")
	s = append(s, "ConnectorHashHex: "+fmt.Sprintf("%#v", this.ConnectorHashHex)+",\n")
	if this.Connector != nil {
		s = append(s, "Connector: "+fmt.Sprintf("%#v", this.Connector)+",\n")
	}
	if this.Operations != nil {
		s = append(s, "Operations: "+fmt.Sprintf("%#v", this.Operations)+",\n")
	}
	if this.Metrics != nil {
		s = append(s, "Metrics: "+fmt.Sprintf("%#v", this.Metrics)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeviceListCmd) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&aranyagopb.DeviceListCmd{")
	s = append(s, "Kind: "+fmt.Sprintf("%#v", this.Kind)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeviceDeleteCmd) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&aranyagopb.DeviceDeleteCmd{")
	s = append(s, "DeviceIds: "+fmt.Sprintf("%#v", this.DeviceIds)+",\n")
	s = append(s, "MetricsReporterHashHexes: "+fmt.Sprintf("%#v", this.MetricsReporterHashHexes)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringCmdDevice(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *DeviceOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Params) > 0 {
		for k := range m.Params {
			v := m.Params[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCmdDevice(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.OperationId) > 0 {
		i -= len(m.OperationId)
		copy(dAtA[i:], m.OperationId)
		i = encodeVarintCmdDevice(dAtA, i, uint64(len(m.OperationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeviceMetric) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceMetric) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceMetric) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReporterParams) > 0 {
		for k := range m.ReporterParams {
			v := m.ReporterParams[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCmdDevice(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ReporterHashHex) > 0 {
		i -= len(m.ReporterHashHex)
		copy(dAtA[i:], m.ReporterHashHex)
		i = encodeVarintCmdDevice(dAtA, i, uint64(len(m.ReporterHashHex)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DeviceParams) > 0 {
		for k := range m.DeviceParams {
			v := m.DeviceParams[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCmdDevice(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ValueType != 0 {
		i = encodeVarintCmdDevice(dAtA, i, uint64(m.ValueType))
		i--
		dAtA[i] = 0x18
	}
	if m.ReportMethod != 0 {
		i = encodeVarintCmdDevice(dAtA, i, uint64(m.ReportMethod))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintCmdDevice(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeviceEnsureCmd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceEnsureCmd) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceEnsureCmd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metrics) > 0 {
		for iNdEx := len(m.Metrics) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Metrics[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCmdDevice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Operations) > 0 {
		for iNdEx := len(m.Operations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Operations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCmdDevice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Connector != nil {
		{
			size, err := m.Connector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCmdDevice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectorHashHex) > 0 {
		i -= len(m.ConnectorHashHex)
		copy(dAtA[i:], m.ConnectorHashHex)
		i = encodeVarintCmdDevice(dAtA, i, uint64(len(m.ConnectorHashHex)))
		i--
		dAtA[i] = 0x12
	}
	if m.Kind != 0 {
		i = encodeVarintCmdDevice(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DeviceListCmd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceListCmd) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceListCmd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Kind != 0 {
		i = encodeVarintCmdDevice(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DeviceDeleteCmd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceDeleteCmd) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceDeleteCmd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetricsReporterHashHexes) > 0 {
		for iNdEx := len(m.MetricsReporterHashHexes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MetricsReporterHashHexes[iNdEx])
			copy(dAtA[i:], m.MetricsReporterHashHexes[iNdEx])
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(m.MetricsReporterHashHexes[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.DeviceIds) > 0 {
		for iNdEx := len(m.DeviceIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DeviceIds[iNdEx])
			copy(dAtA[i:], m.DeviceIds[iNdEx])
			i = encodeVarintCmdDevice(dAtA, i, uint64(len(m.DeviceIds[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintCmdDevice(dAtA []byte, offset int, v uint64) int {
	offset -= sovCmdDevice(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DeviceOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperationId)
	if l > 0 {
		n += 1 + l + sovCmdDevice(uint64(l))
	}
	if len(m.Params) > 0 {
		for k, v := range m.Params {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCmdDevice(uint64(len(k))) + 1 + len(v) + sovCmdDevice(uint64(len(v)))
			n += mapEntrySize + 1 + sovCmdDevice(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *DeviceMetric) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCmdDevice(uint64(l))
	}
	if m.ReportMethod != 0 {
		n += 1 + sovCmdDevice(uint64(m.ReportMethod))
	}
	if m.ValueType != 0 {
		n += 1 + sovCmdDevice(uint64(m.ValueType))
	}
	if len(m.DeviceParams) > 0 {
		for k, v := range m.DeviceParams {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCmdDevice(uint64(len(k))) + 1 + len(v) + sovCmdDevice(uint64(len(v)))
			n += mapEntrySize + 1 + sovCmdDevice(uint64(mapEntrySize))
		}
	}
	l = len(m.ReporterHashHex)
	if l > 0 {
		n += 1 + l + sovCmdDevice(uint64(l))
	}
	if len(m.ReporterParams) > 0 {
		for k, v := range m.ReporterParams {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCmdDevice(uint64(len(k))) + 1 + len(v) + sovCmdDevice(uint64(len(v)))
			n += mapEntrySize + 1 + sovCmdDevice(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *DeviceEnsureCmd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Kind != 0 {
		n += 1 + sovCmdDevice(uint64(m.Kind))
	}
	l = len(m.ConnectorHashHex)
	if l > 0 {
		n += 1 + l + sovCmdDevice(uint64(l))
	}
	if m.Connector != nil {
		l = m.Connector.Size()
		n += 1 + l + sovCmdDevice(uint64(l))
	}
	if len(m.Operations) > 0 {
		for _, e := range m.Operations {
			l = e.Size()
			n += 1 + l + sovCmdDevice(uint64(l))
		}
	}
	if len(m.Metrics) > 0 {
		for _, e := range m.Metrics {
			l = e.Size()
			n += 1 + l + sovCmdDevice(uint64(l))
		}
	}
	return n
}

func (m *DeviceListCmd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Kind != 0 {
		n += 1 + sovCmdDevice(uint64(m.Kind))
	}
	return n
}

func (m *DeviceDeleteCmd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DeviceIds) > 0 {
		for _, s := range m.DeviceIds {
			l = len(s)
			n += 1 + l + sovCmdDevice(uint64(l))
		}
	}
	if len(m.MetricsReporterHashHexes) > 0 {
		for _, s := range m.MetricsReporterHashHexes {
			l = len(s)
			n += 1 + l + sovCmdDevice(uint64(l))
		}
	}
	return n
}

func sovCmdDevice(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCmdDevice(x uint64) (n int) {
	return sovCmdDevice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DeviceOperation) String() string {
	if this == nil {
		return "nil"
	}
	keysForParams := make([]string, 0, len(this.Params))
	for k, _ := range this.Params {
		keysForParams = append(keysForParams, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForParams)
	mapStringForParams := "map[string]string{"
	for _, k := range keysForParams {
		mapStringForParams += fmt.Sprintf("%v: %v,", k, this.Params[k])
	}
	mapStringForParams += "}"
	s := strings.Join([]string{`&DeviceOperation{`,
		`OperationId:` + fmt.Sprintf("%v", this.OperationId) + `,`,
		`Params:` + mapStringForParams + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeviceMetric) String() string {
	if this == nil {
		return "nil"
	}
	keysForDeviceParams := make([]string, 0, len(this.DeviceParams))
	for k, _ := range this.DeviceParams {
		keysForDeviceParams = append(keysForDeviceParams, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForDeviceParams)
	mapStringForDeviceParams := "map[string]string{"
	for _, k := range keysForDeviceParams {
		mapStringForDeviceParams += fmt.Sprintf("%v: %v,", k, this.DeviceParams[k])
	}
	mapStringForDeviceParams += "}"
	keysForReporterParams := make([]string, 0, len(this.ReporterParams))
	for k, _ := range this.ReporterParams {
		keysForReporterParams = append(keysForReporterParams, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForReporterParams)
	mapStringForReporterParams := "map[string]string{"
	for _, k := range keysForReporterParams {
		mapStringForReporterParams += fmt.Sprintf("%v: %v,", k, this.ReporterParams[k])
	}
	mapStringForReporterParams += "}"
	s := strings.Join([]string{`&DeviceMetric{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`ReportMethod:` + fmt.Sprintf("%v", this.ReportMethod) + `,`,
		`ValueType:` + fmt.Sprintf("%v", this.ValueType) + `,`,
		`DeviceParams:` + mapStringForDeviceParams + `,`,
		`ReporterHashHex:` + fmt.Sprintf("%v", this.ReporterHashHex) + `,`,
		`ReporterParams:` + mapStringForReporterParams + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeviceEnsureCmd) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForOperations := "[]*DeviceOperation{"
	for _, f := range this.Operations {
		repeatedStringForOperations += strings.Replace(f.String(), "DeviceOperation", "DeviceOperation", 1) + ","
	}
	repeatedStringForOperations += "}"
	repeatedStringForMetrics := "[]*DeviceMetric{"
	for _, f := range this.Metrics {
		repeatedStringForMetrics += strings.Replace(f.String(), "DeviceMetric", "DeviceMetric", 1) + ","
	}
	repeatedStringForMetrics += "}"
	s := strings.Join([]string{`&DeviceEnsureCmd{`,
		`Kind:` + fmt.Sprintf("%v", this.Kind) + `,`,
		`ConnectorHashHex:` + fmt.Sprintf("%v", this.ConnectorHashHex) + `,`,
		`Connector:` + strings.Replace(fmt.Sprintf("%v", this.Connector), "Connectivity", "Connectivity", 1) + `,`,
		`Operations:` + repeatedStringForOperations + `,`,
		`Metrics:` + repeatedStringForMetrics + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeviceListCmd) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeviceListCmd{`,
		`Kind:` + fmt.Sprintf("%v", this.Kind) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeviceDeleteCmd) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeviceDeleteCmd{`,
		`DeviceIds:` + fmt.Sprintf("%v", this.DeviceIds) + `,`,
		`MetricsReporterHashHexes:` + fmt.Sprintf("%v", this.MetricsReporterHashHexes) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringCmdDevice(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DeviceOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCmdDevice
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCmdDevice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCmdDevice
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCmdDevice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthCmdDevice
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCmdDevice(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Params[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmdDevice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceMetric) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceMetric: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceMetric: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportMethod", wireType)
			}
			m.ReportMethod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportMethod |= DeviceMetric_ReportMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueType", wireType)
			}
			m.ValueType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValueType |= DeviceMetric_ValueType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeviceParams == nil {
				m.DeviceParams = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCmdDevice
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCmdDevice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCmdDevice
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCmdDevice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthCmdDevice
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCmdDevice(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.DeviceParams[mapkey] = mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterHashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReporterHashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReporterParams == nil {
				m.ReporterParams = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCmdDevice
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCmdDevice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCmdDevice
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCmdDevice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthCmdDevice
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCmdDevice(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthCmdDevice
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ReporterParams[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmdDevice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceEnsureCmd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceEnsureCmd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceEnsureCmd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= DeviceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectorHashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectorHashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Connector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Connector == nil {
				m.Connector = &Connectivity{}
			}
			if err := m.Connector.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operations = append(m.Operations, &DeviceOperation{})
			if err := m.Operations[len(m.Operations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metrics = append(m.Metrics, &DeviceMetric{})
			if err := m.Metrics[len(m.Metrics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmdDevice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceListCmd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceListCmd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceListCmd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= DeviceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCmdDevice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceDeleteCmd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceDeleteCmd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceDeleteCmd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceIds = append(m.DeviceIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetricsReporterHashHexes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetricsReporterHashHexes = append(m.MetricsReporterHashHexes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmdDevice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCmdDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCmdDevice(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCmdDevice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmdDevice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCmdDevice
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCmdDevice
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCmdDevice
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCmdDevice        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCmdDevice          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCmdDevice = fmt.Errorf("proto: unexpected end of group")
)
