/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_CMD_POD_PB_H_INCLUDED
#define PB_ARANYA_CMD_POD_PB_H_INCLUDED
#include <pb.h>
#include "cmd_misc.pb.h"
#include "cmd_network.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_ImagePullPolicy {
    aranya_ImagePullPolicy_IMAGE_PULL_ALWAYS = 0,
    aranya_ImagePullPolicy_IMAGE_PULL_IF_NOT_PRESENT = 1,
    aranya_ImagePullPolicy_IMAGE_PULL_NEVER = 2
} aranya_ImagePullPolicy;

typedef enum _aranya_RestartPolicy {
    aranya_RestartPolicy_RESTART_ALWAYS = 0,
    aranya_RestartPolicy_RESTART_ON_FAILURE = 1,
    aranya_RestartPolicy_RESTART_NEVER = 2
} aranya_RestartPolicy;

typedef enum _aranya_PodCmd_Action {
    aranya_PodCmd_Action__INVALID_POD_ACTION = 0,
    aranya_PodCmd_Action_CREATE_CONTAINERS = 1,
    aranya_PodCmd_Action_DELETE_POD = 2,
    aranya_PodCmd_Action_LIST_PODS = 3,
    aranya_PodCmd_Action_ENSURE_IMAGES = 4,
    aranya_PodCmd_Action_DELETE_CONTAINERS = 6,
    aranya_PodCmd_Action_START_POD_SYNC_LOOP = 7
} aranya_PodCmd_Action;

typedef enum _aranya_SecurityOptions_ProcMountKind {
    aranya_SecurityOptions_ProcMountKind_PROC_MOUNT_DEFAULT = 0,
    aranya_SecurityOptions_ProcMountKind_PROC_MOUNT_UNMASKED = 1
} aranya_SecurityOptions_ProcMountKind;

/* Struct definitions */
typedef struct _aranya_ActionMethod_ActionExec {
    pb_callback_t command;
} aranya_ActionMethod_ActionExec;

typedef struct _aranya_ActionMethod_ActionHTTP {
    pb_callback_t method;
    pb_callback_t url;
    pb_callback_t headers;
} aranya_ActionMethod_ActionHTTP;

typedef struct _aranya_ActionMethod_ActionSocket {
    pb_callback_t url;
} aranya_ActionMethod_ActionSocket;

typedef struct _aranya_AuthConfig {
    pb_callback_t username;
    pb_callback_t password;
    pb_callback_t auth;
    pb_callback_t server_address;
    pb_callback_t identity_token;
    pb_callback_t registry_token;
    pb_callback_t email;
} aranya_AuthConfig;

typedef struct _aranya_ContainerSpec_EnvsEntry {
    pb_callback_t key;
    pb_callback_t value;
} aranya_ContainerSpec_EnvsEntry;

typedef struct _aranya_CreateOptions_HostPathsEntry {
    pb_callback_t key;
    pb_callback_t value;
} aranya_CreateOptions_HostPathsEntry;

typedef struct _aranya_CreateOptions_HostsEntry {
    pb_callback_t key;
    pb_callback_t value;
} aranya_CreateOptions_HostsEntry;

typedef struct _aranya_CreateOptions_LabelsEntry {
    pb_callback_t key;
    pb_callback_t value;
} aranya_CreateOptions_LabelsEntry;

typedef struct _aranya_CreateOptions_SysctlsEntry {
    pb_callback_t key;
    pb_callback_t value;
} aranya_CreateOptions_SysctlsEntry;

typedef struct _aranya_ImageEnsureOptions {
    pb_callback_t image_pull;
} aranya_ImageEnsureOptions;

typedef struct _aranya_NamedData {
    pb_callback_t data_map;
} aranya_NamedData;

typedef struct _aranya_NamedData_DataMapEntry {
    pb_callback_t key;
    pb_callback_t value;
} aranya_NamedData_DataMapEntry;

typedef struct _aranya_SELinuxOptions {
    pb_callback_t type;
    pb_callback_t level;
    pb_callback_t role;
    pb_callback_t user;
} aranya_SELinuxOptions;

typedef struct _aranya_ActionMethod {
    pb_size_t which_action;
    union {
        aranya_ActionMethod_ActionExec exec;
        aranya_ActionMethod_ActionHTTP http;
        aranya_ActionMethod_ActionSocket socket;
    } action;
} aranya_ActionMethod;

typedef struct _aranya_ContainerPort {
    pb_callback_t protocol;
    int32_t container_port;
    int32_t host_port;
    pb_callback_t host_ip;
} aranya_ContainerPort;

typedef struct _aranya_CreateOptions {
    pb_callback_t pod_uid;
    pb_callback_t namespace;
    pb_callback_t name;
    aranya_RestartPolicy restart_policy;
    bool host_ipc;
    bool host_network;
    bool host_pid;
    pb_callback_t hostname;
    bool share_pid;
    pb_callback_t containers;
    bool wait_containers;
    pb_callback_t ports;
    pb_callback_t name_servers;
    pb_callback_t search_domains;
    pb_callback_t hosts;
    pb_callback_t dns_options;
    bool has_network_options;
    aranya_NetworkOptions network_options;
    pb_callback_t host_paths;
    pb_callback_t volume_data;
    pb_callback_t labels;
    bool delete_pod_on_failure;
    pb_callback_t sysctls;
} aranya_CreateOptions;

typedef struct _aranya_CreateOptions_VolumeDataEntry {
    pb_callback_t key;
    bool has_value;
    aranya_NamedData value;
} aranya_CreateOptions_VolumeDataEntry;

typedef struct _aranya_DeleteOptions {
    pb_callback_t pod_uid;
    pb_callback_t containers;
    int64_t grace_time;
    pb_callback_t hook_pre_stop;
} aranya_DeleteOptions;

typedef struct _aranya_ImagePull {
    bool has_auth_config;
    aranya_AuthConfig auth_config;
    aranya_ImagePullPolicy pull_policy;
} aranya_ImagePull;

typedef struct _aranya_ListOptions {
    pb_callback_t namespace;
    pb_callback_t name;
    bool all;
} aranya_ListOptions;

typedef struct _aranya_MountOptions {
    pb_callback_t mount_path;
    pb_callback_t sub_path;
    bool read_only;
    pb_callback_t type;
    pb_callback_t options;
    uint32_t file_mode;
    bool remote;
} aranya_MountOptions;

typedef struct _aranya_SecurityOptions {
    bool privileged;
    bool allow_new_privileges;
    bool non_root;
    bool read_only_rootfs;
    int64_t user;
    int64_t group;
    pb_callback_t caps_add;
    pb_callback_t caps_drop;
    aranya_SecurityOptions_ProcMountKind proc_mount_kind;
    bool has_selinux_options;
    aranya_SELinuxOptions selinux_options;
} aranya_SecurityOptions;

typedef struct _aranya_ContainerSpec_MountsEntry {
    pb_callback_t key;
    bool has_value;
    aranya_MountOptions value;
} aranya_ContainerSpec_MountsEntry;

typedef struct _aranya_CreateOptions_PortsEntry {
    pb_callback_t key;
    bool has_value;
    aranya_ContainerPort value;
} aranya_CreateOptions_PortsEntry;

typedef struct _aranya_DeleteOptions_HookPreStopEntry {
    pb_callback_t key;
    bool has_value;
    aranya_ActionMethod value;
} aranya_DeleteOptions_HookPreStopEntry;

typedef struct _aranya_ImageEnsureOptions_ImagePullEntry {
    pb_callback_t key;
    bool has_value;
    aranya_ImagePull value;
} aranya_ImageEnsureOptions_ImagePullEntry;

typedef struct _aranya_PodCmd {
    aranya_PodCmd_Action action;
    pb_size_t which_options;
    union {
        aranya_SyncOptions sync_options;
        aranya_ImageEnsureOptions image_ensure_options;
        aranya_CreateOptions create_options;
        aranya_DeleteOptions delete_options;
        aranya_ListOptions list_options;
    } options;
} aranya_PodCmd;

typedef struct _aranya_Probe {
    bool has_method;
    aranya_ActionMethod method;
    int64_t initial_delay;
    int64_t probe_timeout;
    int64_t probe_interval;
    int32_t success_threshold;
    int32_t failure_threshold;
} aranya_Probe;

typedef struct _aranya_ContainerSpec {
    pb_callback_t image;
    pb_callback_t name;
    pb_callback_t command;
    pb_callback_t args;
    pb_callback_t working_dir;
    bool stdin;
    bool stdin_once;
    bool tty;
    pb_callback_t envs;
    pb_callback_t mounts;
    bool has_readiness_check;
    aranya_Probe readiness_check;
    bool has_liveness_check;
    aranya_Probe liveness_check;
    bool has_security;
    aranya_SecurityOptions security;
    bool has_hook_post_start;
    aranya_ActionMethod hook_post_start;
} aranya_ContainerSpec;


/* Helper constants for enums */
#define _aranya_ImagePullPolicy_MIN aranya_ImagePullPolicy_IMAGE_PULL_ALWAYS
#define _aranya_ImagePullPolicy_MAX aranya_ImagePullPolicy_IMAGE_PULL_NEVER
#define _aranya_ImagePullPolicy_ARRAYSIZE ((aranya_ImagePullPolicy)(aranya_ImagePullPolicy_IMAGE_PULL_NEVER+1))

#define _aranya_RestartPolicy_MIN aranya_RestartPolicy_RESTART_ALWAYS
#define _aranya_RestartPolicy_MAX aranya_RestartPolicy_RESTART_NEVER
#define _aranya_RestartPolicy_ARRAYSIZE ((aranya_RestartPolicy)(aranya_RestartPolicy_RESTART_NEVER+1))

#define _aranya_PodCmd_Action_MIN aranya_PodCmd_Action__INVALID_POD_ACTION
#define _aranya_PodCmd_Action_MAX aranya_PodCmd_Action_START_POD_SYNC_LOOP
#define _aranya_PodCmd_Action_ARRAYSIZE ((aranya_PodCmd_Action)(aranya_PodCmd_Action_START_POD_SYNC_LOOP+1))

#define _aranya_SecurityOptions_ProcMountKind_MIN aranya_SecurityOptions_ProcMountKind_PROC_MOUNT_DEFAULT
#define _aranya_SecurityOptions_ProcMountKind_MAX aranya_SecurityOptions_ProcMountKind_PROC_MOUNT_UNMASKED
#define _aranya_SecurityOptions_ProcMountKind_ARRAYSIZE ((aranya_SecurityOptions_ProcMountKind)(aranya_SecurityOptions_ProcMountKind_PROC_MOUNT_UNMASKED+1))


/* Initializer values for message structs */
#define aranya_PodCmd_init_default               {_aranya_PodCmd_Action_MIN, 0, {aranya_SyncOptions_init_default}}
#define aranya_AuthConfig_init_default           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ImagePull_init_default            {false, aranya_AuthConfig_init_default, _aranya_ImagePullPolicy_MIN}
#define aranya_ImageEnsureOptions_init_default   {{{NULL}, NULL}}
#define aranya_ImageEnsureOptions_ImagePullEntry_init_default {{{NULL}, NULL}, false, aranya_ImagePull_init_default}
#define aranya_NamedData_init_default            {{{NULL}, NULL}}
#define aranya_NamedData_DataMapEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ContainerPort_init_default        {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define aranya_SELinuxOptions_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_SecurityOptions_init_default      {0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, _aranya_SecurityOptions_ProcMountKind_MIN, false, aranya_SELinuxOptions_init_default}
#define aranya_MountOptions_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define aranya_ActionMethod_init_default         {0, {aranya_ActionMethod_ActionExec_init_default}}
#define aranya_ActionMethod_ActionExec_init_default {{{NULL}, NULL}}
#define aranya_ActionMethod_ActionHTTP_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ActionMethod_ActionSocket_init_default {{{NULL}, NULL}}
#define aranya_Probe_init_default                {false, aranya_ActionMethod_init_default, 0, 0, 0, 0, 0}
#define aranya_ContainerSpec_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, aranya_Probe_init_default, false, aranya_Probe_init_default, false, aranya_SecurityOptions_init_default, false, aranya_ActionMethod_init_default}
#define aranya_ContainerSpec_EnvsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ContainerSpec_MountsEntry_init_default {{{NULL}, NULL}, false, aranya_MountOptions_init_default}
#define aranya_CreateOptions_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _aranya_RestartPolicy_MIN, 0, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, aranya_NetworkOptions_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define aranya_CreateOptions_PortsEntry_init_default {{{NULL}, NULL}, false, aranya_ContainerPort_init_default}
#define aranya_CreateOptions_HostsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_CreateOptions_HostPathsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_CreateOptions_VolumeDataEntry_init_default {{{NULL}, NULL}, false, aranya_NamedData_init_default}
#define aranya_CreateOptions_LabelsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_CreateOptions_SysctlsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_DeleteOptions_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define aranya_DeleteOptions_HookPreStopEntry_init_default {{{NULL}, NULL}, false, aranya_ActionMethod_init_default}
#define aranya_ListOptions_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define aranya_PodCmd_init_zero                  {_aranya_PodCmd_Action_MIN, 0, {aranya_SyncOptions_init_zero}}
#define aranya_AuthConfig_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ImagePull_init_zero               {false, aranya_AuthConfig_init_zero, _aranya_ImagePullPolicy_MIN}
#define aranya_ImageEnsureOptions_init_zero      {{{NULL}, NULL}}
#define aranya_ImageEnsureOptions_ImagePullEntry_init_zero {{{NULL}, NULL}, false, aranya_ImagePull_init_zero}
#define aranya_NamedData_init_zero               {{{NULL}, NULL}}
#define aranya_NamedData_DataMapEntry_init_zero  {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ContainerPort_init_zero           {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define aranya_SELinuxOptions_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_SecurityOptions_init_zero         {0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, _aranya_SecurityOptions_ProcMountKind_MIN, false, aranya_SELinuxOptions_init_zero}
#define aranya_MountOptions_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define aranya_ActionMethod_init_zero            {0, {aranya_ActionMethod_ActionExec_init_zero}}
#define aranya_ActionMethod_ActionExec_init_zero {{{NULL}, NULL}}
#define aranya_ActionMethod_ActionHTTP_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ActionMethod_ActionSocket_init_zero {{{NULL}, NULL}}
#define aranya_Probe_init_zero                   {false, aranya_ActionMethod_init_zero, 0, 0, 0, 0, 0}
#define aranya_ContainerSpec_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, aranya_Probe_init_zero, false, aranya_Probe_init_zero, false, aranya_SecurityOptions_init_zero, false, aranya_ActionMethod_init_zero}
#define aranya_ContainerSpec_EnvsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_ContainerSpec_MountsEntry_init_zero {{{NULL}, NULL}, false, aranya_MountOptions_init_zero}
#define aranya_CreateOptions_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _aranya_RestartPolicy_MIN, 0, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, aranya_NetworkOptions_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define aranya_CreateOptions_PortsEntry_init_zero {{{NULL}, NULL}, false, aranya_ContainerPort_init_zero}
#define aranya_CreateOptions_HostsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_CreateOptions_HostPathsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_CreateOptions_VolumeDataEntry_init_zero {{{NULL}, NULL}, false, aranya_NamedData_init_zero}
#define aranya_CreateOptions_LabelsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_CreateOptions_SysctlsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_DeleteOptions_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define aranya_DeleteOptions_HookPreStopEntry_init_zero {{{NULL}, NULL}, false, aranya_ActionMethod_init_zero}
#define aranya_ListOptions_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aranya_ActionMethod_ActionExec_command_tag 1
#define aranya_ActionMethod_ActionHTTP_method_tag 1
#define aranya_ActionMethod_ActionHTTP_url_tag   2
#define aranya_ActionMethod_ActionHTTP_headers_tag 3
#define aranya_ActionMethod_ActionSocket_url_tag 1
#define aranya_AuthConfig_username_tag           1
#define aranya_AuthConfig_password_tag           2
#define aranya_AuthConfig_auth_tag               3
#define aranya_AuthConfig_server_address_tag     4
#define aranya_AuthConfig_identity_token_tag     5
#define aranya_AuthConfig_registry_token_tag     6
#define aranya_AuthConfig_email_tag              7
#define aranya_ContainerSpec_EnvsEntry_key_tag   1
#define aranya_ContainerSpec_EnvsEntry_value_tag 2
#define aranya_CreateOptions_HostPathsEntry_key_tag 1
#define aranya_CreateOptions_HostPathsEntry_value_tag 2
#define aranya_CreateOptions_HostsEntry_key_tag  1
#define aranya_CreateOptions_HostsEntry_value_tag 2
#define aranya_CreateOptions_LabelsEntry_key_tag 1
#define aranya_CreateOptions_LabelsEntry_value_tag 2
#define aranya_CreateOptions_SysctlsEntry_key_tag 1
#define aranya_CreateOptions_SysctlsEntry_value_tag 2
#define aranya_ImageEnsureOptions_image_pull_tag 1
#define aranya_NamedData_data_map_tag            1
#define aranya_NamedData_DataMapEntry_key_tag    1
#define aranya_NamedData_DataMapEntry_value_tag  2
#define aranya_SELinuxOptions_type_tag           1
#define aranya_SELinuxOptions_level_tag          2
#define aranya_SELinuxOptions_role_tag           3
#define aranya_SELinuxOptions_user_tag           4
#define aranya_ActionMethod_exec_tag             1
#define aranya_ActionMethod_http_tag             2
#define aranya_ActionMethod_socket_tag           3
#define aranya_ContainerPort_protocol_tag        1
#define aranya_ContainerPort_container_port_tag  2
#define aranya_ContainerPort_host_port_tag       3
#define aranya_ContainerPort_host_ip_tag         4
#define aranya_CreateOptions_pod_uid_tag         1
#define aranya_CreateOptions_namespace_tag       2
#define aranya_CreateOptions_name_tag            3
#define aranya_CreateOptions_restart_policy_tag  4
#define aranya_CreateOptions_host_ipc_tag        5
#define aranya_CreateOptions_host_network_tag    6
#define aranya_CreateOptions_host_pid_tag        7
#define aranya_CreateOptions_hostname_tag        8
#define aranya_CreateOptions_share_pid_tag       9
#define aranya_CreateOptions_containers_tag      11
#define aranya_CreateOptions_wait_containers_tag 12
#define aranya_CreateOptions_ports_tag           13
#define aranya_CreateOptions_name_servers_tag    14
#define aranya_CreateOptions_search_domains_tag  15
#define aranya_CreateOptions_hosts_tag           16
#define aranya_CreateOptions_dns_options_tag     17
#define aranya_CreateOptions_network_options_tag 18
#define aranya_CreateOptions_host_paths_tag      21
#define aranya_CreateOptions_volume_data_tag     22
#define aranya_CreateOptions_labels_tag          23
#define aranya_CreateOptions_delete_pod_on_failure_tag 24
#define aranya_CreateOptions_sysctls_tag         31
#define aranya_CreateOptions_VolumeDataEntry_key_tag 1
#define aranya_CreateOptions_VolumeDataEntry_value_tag 2
#define aranya_DeleteOptions_pod_uid_tag         1
#define aranya_DeleteOptions_containers_tag      2
#define aranya_DeleteOptions_grace_time_tag      10
#define aranya_DeleteOptions_hook_pre_stop_tag   11
#define aranya_ImagePull_auth_config_tag         2
#define aranya_ImagePull_pull_policy_tag         3
#define aranya_ListOptions_namespace_tag         1
#define aranya_ListOptions_name_tag              2
#define aranya_ListOptions_all_tag               3
#define aranya_MountOptions_mount_path_tag       1
#define aranya_MountOptions_sub_path_tag         2
#define aranya_MountOptions_read_only_tag        3
#define aranya_MountOptions_type_tag             4
#define aranya_MountOptions_options_tag          5
#define aranya_MountOptions_file_mode_tag        6
#define aranya_MountOptions_remote_tag           7
#define aranya_SecurityOptions_privileged_tag    1
#define aranya_SecurityOptions_allow_new_privileges_tag 2
#define aranya_SecurityOptions_non_root_tag      3
#define aranya_SecurityOptions_read_only_rootfs_tag 4
#define aranya_SecurityOptions_user_tag          5
#define aranya_SecurityOptions_group_tag         6
#define aranya_SecurityOptions_caps_add_tag      7
#define aranya_SecurityOptions_caps_drop_tag     8
#define aranya_SecurityOptions_proc_mount_kind_tag 9
#define aranya_SecurityOptions_selinux_options_tag 10
#define aranya_ContainerSpec_MountsEntry_key_tag 1
#define aranya_ContainerSpec_MountsEntry_value_tag 2
#define aranya_CreateOptions_PortsEntry_key_tag  1
#define aranya_CreateOptions_PortsEntry_value_tag 2
#define aranya_DeleteOptions_HookPreStopEntry_key_tag 1
#define aranya_DeleteOptions_HookPreStopEntry_value_tag 2
#define aranya_ImageEnsureOptions_ImagePullEntry_key_tag 1
#define aranya_ImageEnsureOptions_ImagePullEntry_value_tag 2
#define aranya_PodCmd_action_tag                 1
#define aranya_PodCmd_sync_options_tag           2
#define aranya_PodCmd_image_ensure_options_tag   3
#define aranya_PodCmd_create_options_tag         4
#define aranya_PodCmd_delete_options_tag         5
#define aranya_PodCmd_list_options_tag           6
#define aranya_Probe_method_tag                  1
#define aranya_Probe_initial_delay_tag           2
#define aranya_Probe_probe_timeout_tag           3
#define aranya_Probe_probe_interval_tag          4
#define aranya_Probe_success_threshold_tag       5
#define aranya_Probe_failure_threshold_tag       6
#define aranya_ContainerSpec_image_tag           1
#define aranya_ContainerSpec_name_tag            2
#define aranya_ContainerSpec_command_tag         3
#define aranya_ContainerSpec_args_tag            4
#define aranya_ContainerSpec_working_dir_tag     5
#define aranya_ContainerSpec_stdin_tag           6
#define aranya_ContainerSpec_stdin_once_tag      7
#define aranya_ContainerSpec_tty_tag             8
#define aranya_ContainerSpec_envs_tag            11
#define aranya_ContainerSpec_mounts_tag          12
#define aranya_ContainerSpec_readiness_check_tag 13
#define aranya_ContainerSpec_liveness_check_tag  14
#define aranya_ContainerSpec_security_tag        21
#define aranya_ContainerSpec_hook_post_start_tag 31

/* Struct field encoding specification for nanopb */
#define aranya_PodCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,sync_options,options.sync_options),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,image_ensure_options,options.image_ensure_options),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,create_options,options.create_options),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,delete_options,options.delete_options),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,list_options,options.list_options),   6)
#define aranya_PodCmd_CALLBACK NULL
#define aranya_PodCmd_DEFAULT NULL
#define aranya_PodCmd_options_sync_options_MSGTYPE aranya_SyncOptions
#define aranya_PodCmd_options_image_ensure_options_MSGTYPE aranya_ImageEnsureOptions
#define aranya_PodCmd_options_create_options_MSGTYPE aranya_CreateOptions
#define aranya_PodCmd_options_delete_options_MSGTYPE aranya_DeleteOptions
#define aranya_PodCmd_options_list_options_MSGTYPE aranya_ListOptions

#define aranya_AuthConfig_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   username,          1) \
X(a, CALLBACK, SINGULAR, STRING,   password,          2) \
X(a, CALLBACK, SINGULAR, STRING,   auth,              3) \
X(a, CALLBACK, SINGULAR, STRING,   server_address,    4) \
X(a, CALLBACK, SINGULAR, STRING,   identity_token,    5) \
X(a, CALLBACK, SINGULAR, STRING,   registry_token,    6) \
X(a, CALLBACK, SINGULAR, STRING,   email,             7)
#define aranya_AuthConfig_CALLBACK pb_default_field_callback
#define aranya_AuthConfig_DEFAULT NULL

#define aranya_ImagePull_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  auth_config,       2) \
X(a, STATIC,   SINGULAR, UENUM,    pull_policy,       3)
#define aranya_ImagePull_CALLBACK NULL
#define aranya_ImagePull_DEFAULT NULL
#define aranya_ImagePull_auth_config_MSGTYPE aranya_AuthConfig

#define aranya_ImageEnsureOptions_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  image_pull,        1)
#define aranya_ImageEnsureOptions_CALLBACK pb_default_field_callback
#define aranya_ImageEnsureOptions_DEFAULT NULL
#define aranya_ImageEnsureOptions_image_pull_MSGTYPE aranya_ImageEnsureOptions_ImagePullEntry

#define aranya_ImageEnsureOptions_ImagePullEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define aranya_ImageEnsureOptions_ImagePullEntry_CALLBACK pb_default_field_callback
#define aranya_ImageEnsureOptions_ImagePullEntry_DEFAULT NULL
#define aranya_ImageEnsureOptions_ImagePullEntry_value_MSGTYPE aranya_ImagePull

#define aranya_NamedData_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  data_map,          1)
#define aranya_NamedData_CALLBACK pb_default_field_callback
#define aranya_NamedData_DEFAULT NULL
#define aranya_NamedData_data_map_MSGTYPE aranya_NamedData_DataMapEntry

#define aranya_NamedData_DataMapEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             2)
#define aranya_NamedData_DataMapEntry_CALLBACK pb_default_field_callback
#define aranya_NamedData_DataMapEntry_DEFAULT NULL

#define aranya_ContainerPort_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   protocol,          1) \
X(a, STATIC,   SINGULAR, INT32,    container_port,    2) \
X(a, STATIC,   SINGULAR, INT32,    host_port,         3) \
X(a, CALLBACK, SINGULAR, STRING,   host_ip,           4)
#define aranya_ContainerPort_CALLBACK pb_default_field_callback
#define aranya_ContainerPort_DEFAULT NULL

#define aranya_SELinuxOptions_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   level,             2) \
X(a, CALLBACK, SINGULAR, STRING,   role,              3) \
X(a, CALLBACK, SINGULAR, STRING,   user,              4)
#define aranya_SELinuxOptions_CALLBACK pb_default_field_callback
#define aranya_SELinuxOptions_DEFAULT NULL

#define aranya_SecurityOptions_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     privileged,        1) \
X(a, STATIC,   SINGULAR, BOOL,     allow_new_privileges,   2) \
X(a, STATIC,   SINGULAR, BOOL,     non_root,          3) \
X(a, STATIC,   SINGULAR, BOOL,     read_only_rootfs,   4) \
X(a, STATIC,   SINGULAR, INT64,    user,              5) \
X(a, STATIC,   SINGULAR, INT64,    group,             6) \
X(a, CALLBACK, REPEATED, STRING,   caps_add,          7) \
X(a, CALLBACK, REPEATED, STRING,   caps_drop,         8) \
X(a, STATIC,   SINGULAR, UENUM,    proc_mount_kind,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  selinux_options,  10)
#define aranya_SecurityOptions_CALLBACK pb_default_field_callback
#define aranya_SecurityOptions_DEFAULT NULL
#define aranya_SecurityOptions_selinux_options_MSGTYPE aranya_SELinuxOptions

#define aranya_MountOptions_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   mount_path,        1) \
X(a, CALLBACK, SINGULAR, STRING,   sub_path,          2) \
X(a, STATIC,   SINGULAR, BOOL,     read_only,         3) \
X(a, CALLBACK, SINGULAR, STRING,   type,              4) \
X(a, CALLBACK, REPEATED, STRING,   options,           5) \
X(a, STATIC,   SINGULAR, UINT32,   file_mode,         6) \
X(a, STATIC,   SINGULAR, BOOL,     remote,            7)
#define aranya_MountOptions_CALLBACK pb_default_field_callback
#define aranya_MountOptions_DEFAULT NULL

#define aranya_ActionMethod_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (action,exec,action.exec),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (action,http,action.http),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (action,socket,action.socket),   3)
#define aranya_ActionMethod_CALLBACK NULL
#define aranya_ActionMethod_DEFAULT NULL
#define aranya_ActionMethod_action_exec_MSGTYPE aranya_ActionMethod_ActionExec
#define aranya_ActionMethod_action_http_MSGTYPE aranya_ActionMethod_ActionHTTP
#define aranya_ActionMethod_action_socket_MSGTYPE aranya_ActionMethod_ActionSocket

#define aranya_ActionMethod_ActionExec_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   command,           1)
#define aranya_ActionMethod_ActionExec_CALLBACK pb_default_field_callback
#define aranya_ActionMethod_ActionExec_DEFAULT NULL

#define aranya_ActionMethod_ActionHTTP_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   method,            1) \
X(a, CALLBACK, SINGULAR, STRING,   url,               2) \
X(a, CALLBACK, REPEATED, MESSAGE,  headers,           3)
#define aranya_ActionMethod_ActionHTTP_CALLBACK pb_default_field_callback
#define aranya_ActionMethod_ActionHTTP_DEFAULT NULL
#define aranya_ActionMethod_ActionHTTP_headers_MSGTYPE aranya_KeyValuePair

#define aranya_ActionMethod_ActionSocket_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   url,               1)
#define aranya_ActionMethod_ActionSocket_CALLBACK pb_default_field_callback
#define aranya_ActionMethod_ActionSocket_DEFAULT NULL

#define aranya_Probe_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  method,            1) \
X(a, STATIC,   SINGULAR, INT64,    initial_delay,     2) \
X(a, STATIC,   SINGULAR, INT64,    probe_timeout,     3) \
X(a, STATIC,   SINGULAR, INT64,    probe_interval,    4) \
X(a, STATIC,   SINGULAR, INT32,    success_threshold,   5) \
X(a, STATIC,   SINGULAR, INT32,    failure_threshold,   6)
#define aranya_Probe_CALLBACK NULL
#define aranya_Probe_DEFAULT NULL
#define aranya_Probe_method_MSGTYPE aranya_ActionMethod

#define aranya_ContainerSpec_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   image,             1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, REPEATED, STRING,   command,           3) \
X(a, CALLBACK, REPEATED, STRING,   args,              4) \
X(a, CALLBACK, SINGULAR, STRING,   working_dir,       5) \
X(a, STATIC,   SINGULAR, BOOL,     stdin,             6) \
X(a, STATIC,   SINGULAR, BOOL,     stdin_once,        7) \
X(a, STATIC,   SINGULAR, BOOL,     tty,               8) \
X(a, CALLBACK, REPEATED, MESSAGE,  envs,             11) \
X(a, CALLBACK, REPEATED, MESSAGE,  mounts,           12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  readiness_check,  13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  liveness_check,   14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  security,         21) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hook_post_start,  31)
#define aranya_ContainerSpec_CALLBACK pb_default_field_callback
#define aranya_ContainerSpec_DEFAULT NULL
#define aranya_ContainerSpec_envs_MSGTYPE aranya_ContainerSpec_EnvsEntry
#define aranya_ContainerSpec_mounts_MSGTYPE aranya_ContainerSpec_MountsEntry
#define aranya_ContainerSpec_readiness_check_MSGTYPE aranya_Probe
#define aranya_ContainerSpec_liveness_check_MSGTYPE aranya_Probe
#define aranya_ContainerSpec_security_MSGTYPE aranya_SecurityOptions
#define aranya_ContainerSpec_hook_post_start_MSGTYPE aranya_ActionMethod

#define aranya_ContainerSpec_EnvsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define aranya_ContainerSpec_EnvsEntry_CALLBACK pb_default_field_callback
#define aranya_ContainerSpec_EnvsEntry_DEFAULT NULL

#define aranya_ContainerSpec_MountsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define aranya_ContainerSpec_MountsEntry_CALLBACK pb_default_field_callback
#define aranya_ContainerSpec_MountsEntry_DEFAULT NULL
#define aranya_ContainerSpec_MountsEntry_value_MSGTYPE aranya_MountOptions

#define aranya_CreateOptions_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   pod_uid,           1) \
X(a, CALLBACK, SINGULAR, STRING,   namespace,         2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3) \
X(a, STATIC,   SINGULAR, UENUM,    restart_policy,    4) \
X(a, STATIC,   SINGULAR, BOOL,     host_ipc,          5) \
X(a, STATIC,   SINGULAR, BOOL,     host_network,      6) \
X(a, STATIC,   SINGULAR, BOOL,     host_pid,          7) \
X(a, CALLBACK, SINGULAR, STRING,   hostname,          8) \
X(a, STATIC,   SINGULAR, BOOL,     share_pid,         9) \
X(a, CALLBACK, REPEATED, MESSAGE,  containers,       11) \
X(a, STATIC,   SINGULAR, BOOL,     wait_containers,  12) \
X(a, CALLBACK, REPEATED, MESSAGE,  ports,            13) \
X(a, CALLBACK, REPEATED, STRING,   name_servers,     14) \
X(a, CALLBACK, REPEATED, STRING,   search_domains,   15) \
X(a, CALLBACK, REPEATED, MESSAGE,  hosts,            16) \
X(a, CALLBACK, REPEATED, STRING,   dns_options,      17) \
X(a, STATIC,   OPTIONAL, MESSAGE,  network_options,  18) \
X(a, CALLBACK, REPEATED, MESSAGE,  host_paths,       21) \
X(a, CALLBACK, REPEATED, MESSAGE,  volume_data,      22) \
X(a, CALLBACK, REPEATED, MESSAGE,  labels,           23) \
X(a, STATIC,   SINGULAR, BOOL,     delete_pod_on_failure,  24) \
X(a, CALLBACK, REPEATED, MESSAGE,  sysctls,          31)
#define aranya_CreateOptions_CALLBACK pb_default_field_callback
#define aranya_CreateOptions_DEFAULT NULL
#define aranya_CreateOptions_containers_MSGTYPE aranya_ContainerSpec
#define aranya_CreateOptions_ports_MSGTYPE aranya_CreateOptions_PortsEntry
#define aranya_CreateOptions_hosts_MSGTYPE aranya_CreateOptions_HostsEntry
#define aranya_CreateOptions_network_options_MSGTYPE aranya_NetworkOptions
#define aranya_CreateOptions_host_paths_MSGTYPE aranya_CreateOptions_HostPathsEntry
#define aranya_CreateOptions_volume_data_MSGTYPE aranya_CreateOptions_VolumeDataEntry
#define aranya_CreateOptions_labels_MSGTYPE aranya_CreateOptions_LabelsEntry
#define aranya_CreateOptions_sysctls_MSGTYPE aranya_CreateOptions_SysctlsEntry

#define aranya_CreateOptions_PortsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define aranya_CreateOptions_PortsEntry_CALLBACK pb_default_field_callback
#define aranya_CreateOptions_PortsEntry_DEFAULT NULL
#define aranya_CreateOptions_PortsEntry_value_MSGTYPE aranya_ContainerPort

#define aranya_CreateOptions_HostsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define aranya_CreateOptions_HostsEntry_CALLBACK pb_default_field_callback
#define aranya_CreateOptions_HostsEntry_DEFAULT NULL

#define aranya_CreateOptions_HostPathsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define aranya_CreateOptions_HostPathsEntry_CALLBACK pb_default_field_callback
#define aranya_CreateOptions_HostPathsEntry_DEFAULT NULL

#define aranya_CreateOptions_VolumeDataEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define aranya_CreateOptions_VolumeDataEntry_CALLBACK pb_default_field_callback
#define aranya_CreateOptions_VolumeDataEntry_DEFAULT NULL
#define aranya_CreateOptions_VolumeDataEntry_value_MSGTYPE aranya_NamedData

#define aranya_CreateOptions_LabelsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define aranya_CreateOptions_LabelsEntry_CALLBACK pb_default_field_callback
#define aranya_CreateOptions_LabelsEntry_DEFAULT NULL

#define aranya_CreateOptions_SysctlsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define aranya_CreateOptions_SysctlsEntry_CALLBACK pb_default_field_callback
#define aranya_CreateOptions_SysctlsEntry_DEFAULT NULL

#define aranya_DeleteOptions_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   pod_uid,           1) \
X(a, CALLBACK, REPEATED, STRING,   containers,        2) \
X(a, STATIC,   SINGULAR, INT64,    grace_time,       10) \
X(a, CALLBACK, REPEATED, MESSAGE,  hook_pre_stop,    11)
#define aranya_DeleteOptions_CALLBACK pb_default_field_callback
#define aranya_DeleteOptions_DEFAULT NULL
#define aranya_DeleteOptions_hook_pre_stop_MSGTYPE aranya_DeleteOptions_HookPreStopEntry

#define aranya_DeleteOptions_HookPreStopEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define aranya_DeleteOptions_HookPreStopEntry_CALLBACK pb_default_field_callback
#define aranya_DeleteOptions_HookPreStopEntry_DEFAULT NULL
#define aranya_DeleteOptions_HookPreStopEntry_value_MSGTYPE aranya_ActionMethod

#define aranya_ListOptions_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   namespace,         1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, BOOL,     all,               3)
#define aranya_ListOptions_CALLBACK pb_default_field_callback
#define aranya_ListOptions_DEFAULT NULL

extern const pb_msgdesc_t aranya_PodCmd_msg;
extern const pb_msgdesc_t aranya_AuthConfig_msg;
extern const pb_msgdesc_t aranya_ImagePull_msg;
extern const pb_msgdesc_t aranya_ImageEnsureOptions_msg;
extern const pb_msgdesc_t aranya_ImageEnsureOptions_ImagePullEntry_msg;
extern const pb_msgdesc_t aranya_NamedData_msg;
extern const pb_msgdesc_t aranya_NamedData_DataMapEntry_msg;
extern const pb_msgdesc_t aranya_ContainerPort_msg;
extern const pb_msgdesc_t aranya_SELinuxOptions_msg;
extern const pb_msgdesc_t aranya_SecurityOptions_msg;
extern const pb_msgdesc_t aranya_MountOptions_msg;
extern const pb_msgdesc_t aranya_ActionMethod_msg;
extern const pb_msgdesc_t aranya_ActionMethod_ActionExec_msg;
extern const pb_msgdesc_t aranya_ActionMethod_ActionHTTP_msg;
extern const pb_msgdesc_t aranya_ActionMethod_ActionSocket_msg;
extern const pb_msgdesc_t aranya_Probe_msg;
extern const pb_msgdesc_t aranya_ContainerSpec_msg;
extern const pb_msgdesc_t aranya_ContainerSpec_EnvsEntry_msg;
extern const pb_msgdesc_t aranya_ContainerSpec_MountsEntry_msg;
extern const pb_msgdesc_t aranya_CreateOptions_msg;
extern const pb_msgdesc_t aranya_CreateOptions_PortsEntry_msg;
extern const pb_msgdesc_t aranya_CreateOptions_HostsEntry_msg;
extern const pb_msgdesc_t aranya_CreateOptions_HostPathsEntry_msg;
extern const pb_msgdesc_t aranya_CreateOptions_VolumeDataEntry_msg;
extern const pb_msgdesc_t aranya_CreateOptions_LabelsEntry_msg;
extern const pb_msgdesc_t aranya_CreateOptions_SysctlsEntry_msg;
extern const pb_msgdesc_t aranya_DeleteOptions_msg;
extern const pb_msgdesc_t aranya_DeleteOptions_HookPreStopEntry_msg;
extern const pb_msgdesc_t aranya_ListOptions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aranya_PodCmd_fields &aranya_PodCmd_msg
#define aranya_AuthConfig_fields &aranya_AuthConfig_msg
#define aranya_ImagePull_fields &aranya_ImagePull_msg
#define aranya_ImageEnsureOptions_fields &aranya_ImageEnsureOptions_msg
#define aranya_ImageEnsureOptions_ImagePullEntry_fields &aranya_ImageEnsureOptions_ImagePullEntry_msg
#define aranya_NamedData_fields &aranya_NamedData_msg
#define aranya_NamedData_DataMapEntry_fields &aranya_NamedData_DataMapEntry_msg
#define aranya_ContainerPort_fields &aranya_ContainerPort_msg
#define aranya_SELinuxOptions_fields &aranya_SELinuxOptions_msg
#define aranya_SecurityOptions_fields &aranya_SecurityOptions_msg
#define aranya_MountOptions_fields &aranya_MountOptions_msg
#define aranya_ActionMethod_fields &aranya_ActionMethod_msg
#define aranya_ActionMethod_ActionExec_fields &aranya_ActionMethod_ActionExec_msg
#define aranya_ActionMethod_ActionHTTP_fields &aranya_ActionMethod_ActionHTTP_msg
#define aranya_ActionMethod_ActionSocket_fields &aranya_ActionMethod_ActionSocket_msg
#define aranya_Probe_fields &aranya_Probe_msg
#define aranya_ContainerSpec_fields &aranya_ContainerSpec_msg
#define aranya_ContainerSpec_EnvsEntry_fields &aranya_ContainerSpec_EnvsEntry_msg
#define aranya_ContainerSpec_MountsEntry_fields &aranya_ContainerSpec_MountsEntry_msg
#define aranya_CreateOptions_fields &aranya_CreateOptions_msg
#define aranya_CreateOptions_PortsEntry_fields &aranya_CreateOptions_PortsEntry_msg
#define aranya_CreateOptions_HostsEntry_fields &aranya_CreateOptions_HostsEntry_msg
#define aranya_CreateOptions_HostPathsEntry_fields &aranya_CreateOptions_HostPathsEntry_msg
#define aranya_CreateOptions_VolumeDataEntry_fields &aranya_CreateOptions_VolumeDataEntry_msg
#define aranya_CreateOptions_LabelsEntry_fields &aranya_CreateOptions_LabelsEntry_msg
#define aranya_CreateOptions_SysctlsEntry_fields &aranya_CreateOptions_SysctlsEntry_msg
#define aranya_DeleteOptions_fields &aranya_DeleteOptions_msg
#define aranya_DeleteOptions_HookPreStopEntry_fields &aranya_DeleteOptions_HookPreStopEntry_msg
#define aranya_ListOptions_fields &aranya_ListOptions_msg

/* Maximum encoded size of messages (where known) */
/* aranya_PodCmd_size depends on runtime parameters */
/* aranya_AuthConfig_size depends on runtime parameters */
/* aranya_ImagePull_size depends on runtime parameters */
/* aranya_ImageEnsureOptions_size depends on runtime parameters */
/* aranya_ImageEnsureOptions_ImagePullEntry_size depends on runtime parameters */
/* aranya_NamedData_size depends on runtime parameters */
/* aranya_NamedData_DataMapEntry_size depends on runtime parameters */
/* aranya_ContainerPort_size depends on runtime parameters */
/* aranya_SELinuxOptions_size depends on runtime parameters */
/* aranya_SecurityOptions_size depends on runtime parameters */
/* aranya_MountOptions_size depends on runtime parameters */
/* aranya_ActionMethod_size depends on runtime parameters */
/* aranya_ActionMethod_ActionExec_size depends on runtime parameters */
/* aranya_ActionMethod_ActionHTTP_size depends on runtime parameters */
/* aranya_ActionMethod_ActionSocket_size depends on runtime parameters */
/* aranya_Probe_size depends on runtime parameters */
/* aranya_ContainerSpec_size depends on runtime parameters */
/* aranya_ContainerSpec_EnvsEntry_size depends on runtime parameters */
/* aranya_ContainerSpec_MountsEntry_size depends on runtime parameters */
/* aranya_CreateOptions_size depends on runtime parameters */
/* aranya_CreateOptions_PortsEntry_size depends on runtime parameters */
/* aranya_CreateOptions_HostsEntry_size depends on runtime parameters */
/* aranya_CreateOptions_HostPathsEntry_size depends on runtime parameters */
/* aranya_CreateOptions_VolumeDataEntry_size depends on runtime parameters */
/* aranya_CreateOptions_LabelsEntry_size depends on runtime parameters */
/* aranya_CreateOptions_SysctlsEntry_size depends on runtime parameters */
/* aranya_DeleteOptions_size depends on runtime parameters */
/* aranya_DeleteOptions_HookPreStopEntry_size depends on runtime parameters */
/* aranya_ListOptions_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
