/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "cmd_network_container.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aranya_ContainerNetworkListCmd, aranya_ContainerNetworkListCmd, AUTO)


PB_BIND(aranya_ContainerNetworkEnsureCmd, aranya_ContainerNetworkEnsureCmd, AUTO)



