/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_DEVICE_PB_H_INCLUDED
#define PB_ARANYA_DEVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_DeviceType {
    aranya_DeviceType__INVALID_DEVICE_TYPE = 0,
    aranya_DeviceType_DEVICE_TYPE_NORMAL = 1,
    aranya_DeviceType_DEVICE_TYPE_METRICS_REPORTER = 2
} aranya_DeviceType;

/* Helper constants for enums */
#define _aranya_DeviceType_MIN aranya_DeviceType__INVALID_DEVICE_TYPE
#define _aranya_DeviceType_MAX aranya_DeviceType_DEVICE_TYPE_METRICS_REPORTER
#define _aranya_DeviceType_ARRAYSIZE ((aranya_DeviceType)(aranya_DeviceType_DEVICE_TYPE_METRICS_REPORTER+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
