/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_MSG_STORAGE_PB_H_INCLUDED
#define PB_ARANYA_MSG_STORAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_StorageStatusMsg_State {
    aranya_StorageStatusMsg_State_VOLUME_UNKONW = 0,
    aranya_StorageStatusMsg_State_VOLUME_UNMOUNTED = 1,
    aranya_StorageStatusMsg_State_VOLUME_MOUNTED = 2
} aranya_StorageStatusMsg_State;

/* Struct definitions */
typedef struct _aranya_StorageStatusListMsg {
    pb_callback_t storages;
} aranya_StorageStatusListMsg;

typedef struct _aranya_StorageStatusMsg {
    aranya_StorageStatusMsg_State state;
    pb_callback_t remote_path;
    pb_callback_t mount_point;
} aranya_StorageStatusMsg;


/* Helper constants for enums */
#define _aranya_StorageStatusMsg_State_MIN aranya_StorageStatusMsg_State_VOLUME_UNKONW
#define _aranya_StorageStatusMsg_State_MAX aranya_StorageStatusMsg_State_VOLUME_MOUNTED
#define _aranya_StorageStatusMsg_State_ARRAYSIZE ((aranya_StorageStatusMsg_State)(aranya_StorageStatusMsg_State_VOLUME_MOUNTED+1))


/* Initializer values for message structs */
#define aranya_StorageStatusMsg_init_default     {_aranya_StorageStatusMsg_State_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_StorageStatusListMsg_init_default {{{NULL}, NULL}}
#define aranya_StorageStatusMsg_init_zero        {_aranya_StorageStatusMsg_State_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_StorageStatusListMsg_init_zero    {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define aranya_StorageStatusListMsg_storages_tag 1
#define aranya_StorageStatusMsg_state_tag        1
#define aranya_StorageStatusMsg_remote_path_tag  2
#define aranya_StorageStatusMsg_mount_point_tag  3

/* Struct field encoding specification for nanopb */
#define aranya_StorageStatusMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, CALLBACK, SINGULAR, STRING,   remote_path,       2) \
X(a, CALLBACK, SINGULAR, STRING,   mount_point,       3)
#define aranya_StorageStatusMsg_CALLBACK pb_default_field_callback
#define aranya_StorageStatusMsg_DEFAULT NULL

#define aranya_StorageStatusListMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  storages,          1)
#define aranya_StorageStatusListMsg_CALLBACK pb_default_field_callback
#define aranya_StorageStatusListMsg_DEFAULT NULL
#define aranya_StorageStatusListMsg_storages_MSGTYPE aranya_StorageStatusMsg

extern const pb_msgdesc_t aranya_StorageStatusMsg_msg;
extern const pb_msgdesc_t aranya_StorageStatusListMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aranya_StorageStatusMsg_fields &aranya_StorageStatusMsg_msg
#define aranya_StorageStatusListMsg_fields &aranya_StorageStatusListMsg_msg

/* Maximum encoded size of messages (where known) */
/* aranya_StorageStatusMsg_size depends on runtime parameters */
/* aranya_StorageStatusListMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
