/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "msg_device.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aranya_DeviceStatusMsg, aranya_DeviceStatusMsg, AUTO)


PB_BIND(aranya_DeviceStatusListMsg, aranya_DeviceStatusListMsg, AUTO)




