/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "msg_storage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aranya_StorageStatus, aranya_StorageStatus, AUTO)


PB_BIND(aranya_StorageStatusList, aranya_StorageStatusList, AUTO)




