/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_MSG_POD_PB_H_INCLUDED
#define PB_ARANYA_MSG_POD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_PodState {
    aranya_PodState_POD_STATE_UNKNOWN = 0,
    aranya_PodState_POD_STATE_PENDING = 1,
    aranya_PodState_POD_STATE_RUNNING = 2,
    aranya_PodState_POD_STATE_SUCCEEDED = 3,
    aranya_PodState_POD_STATE_FAILED = 4
} aranya_PodState;

/* Struct definitions */
typedef struct _aranya_PodStatusListMsg {
    pb_callback_t pods;
} aranya_PodStatusListMsg;

typedef struct _aranya_PodStatusMsg {
    pb_callback_t uid;
    pb_callback_t ipv4;
    pb_callback_t ipv6;
    pb_callback_t containers;
} aranya_PodStatusMsg;

typedef struct _aranya_ContainerStatus {
    pb_callback_t container_id;
    pb_callback_t image_id;
    pb_callback_t created_at;
    pb_callback_t started_at;
    pb_callback_t finished_at;
    int32_t exit_code;
    int32_t restart_count;
    pb_callback_t reason;
    pb_callback_t message;
} aranya_ContainerStatus;

typedef struct _aranya_PodStatusMsg_ContainersEntry {
    pb_callback_t key;
    bool has_value;
    aranya_ContainerStatus value;
} aranya_PodStatusMsg_ContainersEntry;


/* Helper constants for enums */
#define _aranya_PodState_MIN aranya_PodState_POD_STATE_UNKNOWN
#define _aranya_PodState_MAX aranya_PodState_POD_STATE_FAILED
#define _aranya_PodState_ARRAYSIZE ((aranya_PodState)(aranya_PodState_POD_STATE_FAILED+1))


/* Initializer values for message structs */
#define aranya_ContainerStatus_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_PodStatusMsg_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_PodStatusMsg_ContainersEntry_init_default {{{NULL}, NULL}, false, aranya_ContainerStatus_init_default}
#define aranya_PodStatusListMsg_init_default     {{{NULL}, NULL}}
#define aranya_ContainerStatus_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_PodStatusMsg_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_PodStatusMsg_ContainersEntry_init_zero {{{NULL}, NULL}, false, aranya_ContainerStatus_init_zero}
#define aranya_PodStatusListMsg_init_zero        {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define aranya_PodStatusListMsg_pods_tag         1
#define aranya_PodStatusMsg_uid_tag              1
#define aranya_PodStatusMsg_ipv4_tag             2
#define aranya_PodStatusMsg_ipv6_tag             3
#define aranya_PodStatusMsg_containers_tag       4
#define aranya_ContainerStatus_container_id_tag  1
#define aranya_ContainerStatus_image_id_tag      2
#define aranya_ContainerStatus_created_at_tag    4
#define aranya_ContainerStatus_started_at_tag    5
#define aranya_ContainerStatus_finished_at_tag   6
#define aranya_ContainerStatus_exit_code_tag     7
#define aranya_ContainerStatus_restart_count_tag 8
#define aranya_ContainerStatus_reason_tag        11
#define aranya_ContainerStatus_message_tag       12
#define aranya_PodStatusMsg_ContainersEntry_key_tag 1
#define aranya_PodStatusMsg_ContainersEntry_value_tag 2

/* Struct field encoding specification for nanopb */
#define aranya_ContainerStatus_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   container_id,      1) \
X(a, CALLBACK, SINGULAR, STRING,   image_id,          2) \
X(a, CALLBACK, SINGULAR, STRING,   created_at,        4) \
X(a, CALLBACK, SINGULAR, STRING,   started_at,        5) \
X(a, CALLBACK, SINGULAR, STRING,   finished_at,       6) \
X(a, STATIC,   SINGULAR, INT32,    exit_code,         7) \
X(a, STATIC,   SINGULAR, INT32,    restart_count,     8) \
X(a, CALLBACK, SINGULAR, STRING,   reason,           11) \
X(a, CALLBACK, SINGULAR, STRING,   message,          12)
#define aranya_ContainerStatus_CALLBACK pb_default_field_callback
#define aranya_ContainerStatus_DEFAULT NULL

#define aranya_PodStatusMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   uid,               1) \
X(a, CALLBACK, SINGULAR, STRING,   ipv4,              2) \
X(a, CALLBACK, SINGULAR, STRING,   ipv6,              3) \
X(a, CALLBACK, REPEATED, MESSAGE,  containers,        4)
#define aranya_PodStatusMsg_CALLBACK pb_default_field_callback
#define aranya_PodStatusMsg_DEFAULT NULL
#define aranya_PodStatusMsg_containers_MSGTYPE aranya_PodStatusMsg_ContainersEntry

#define aranya_PodStatusMsg_ContainersEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define aranya_PodStatusMsg_ContainersEntry_CALLBACK pb_default_field_callback
#define aranya_PodStatusMsg_ContainersEntry_DEFAULT NULL
#define aranya_PodStatusMsg_ContainersEntry_value_MSGTYPE aranya_ContainerStatus

#define aranya_PodStatusListMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  pods,              1)
#define aranya_PodStatusListMsg_CALLBACK pb_default_field_callback
#define aranya_PodStatusListMsg_DEFAULT NULL
#define aranya_PodStatusListMsg_pods_MSGTYPE aranya_PodStatusMsg

extern const pb_msgdesc_t aranya_ContainerStatus_msg;
extern const pb_msgdesc_t aranya_PodStatusMsg_msg;
extern const pb_msgdesc_t aranya_PodStatusMsg_ContainersEntry_msg;
extern const pb_msgdesc_t aranya_PodStatusListMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aranya_ContainerStatus_fields &aranya_ContainerStatus_msg
#define aranya_PodStatusMsg_fields &aranya_PodStatusMsg_msg
#define aranya_PodStatusMsg_ContainersEntry_fields &aranya_PodStatusMsg_ContainersEntry_msg
#define aranya_PodStatusListMsg_fields &aranya_PodStatusListMsg_msg

/* Maximum encoded size of messages (where known) */
/* aranya_ContainerStatus_size depends on runtime parameters */
/* aranya_PodStatusMsg_size depends on runtime parameters */
/* aranya_PodStatusMsg_ContainersEntry_size depends on runtime parameters */
/* aranya_PodStatusListMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
