/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "msg_pod.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aranya_ContainerStatus, aranya_ContainerStatus, AUTO)


PB_BIND(aranya_PodStatusMsg, aranya_PodStatusMsg, AUTO)


PB_BIND(aranya_PodStatusMsg_ContainersEntry, aranya_PodStatusMsg_ContainersEntry, AUTO)


PB_BIND(aranya_PodStatusListMsg, aranya_PodStatusListMsg, AUTO)




