# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_network_container.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg_network_container.proto',
  package='aranya',
  syntax='proto3',
  serialized_options=b'Z!arhat.dev/aranya-proto/aranyagopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bmsg_network_container.proto\x12\x06\x61ranya\"A\n\x19\x43ontainerNetworkStatusMsg\x12\x11\n\tipv4_cidr\x18\x01 \x01(\t\x12\x11\n\tipv6_cidr\x18\x02 \x01(\tB#Z!arhat.dev/aranya-proto/aranyagopbb\x06proto3'
)




_CONTAINERNETWORKSTATUSMSG = _descriptor.Descriptor(
  name='ContainerNetworkStatusMsg',
  full_name='aranya.ContainerNetworkStatusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ipv4_cidr', full_name='aranya.ContainerNetworkStatusMsg.ipv4_cidr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ipv6_cidr', full_name='aranya.ContainerNetworkStatusMsg.ipv6_cidr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['ContainerNetworkStatusMsg'] = _CONTAINERNETWORKSTATUSMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContainerNetworkStatusMsg = _reflection.GeneratedProtocolMessageType('ContainerNetworkStatusMsg', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERNETWORKSTATUSMSG,
  '__module__' : 'msg_network_container_pb2'
  # @@protoc_insertion_point(class_scope:aranya.ContainerNetworkStatusMsg)
  })
_sym_db.RegisterMessage(ContainerNetworkStatusMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
