# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peripheral.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peripheral.proto',
  package='aranya',
  syntax='proto3',
  serialized_options=b'Z!arhat.dev/aranya-proto/aranyagopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10peripheral.proto\x12\x06\x61ranya*p\n\x0ePeripheralType\x12\x1c\n\x18_INVALID_PERIPHERAL_TYPE\x10\x00\x12\x1a\n\x16PERIPHERAL_TYPE_NORMAL\x10\x01\x12$\n PERIPHERAL_TYPE_METRICS_REPORTER\x10\x02\x42#Z!arhat.dev/aranya-proto/aranyagopbb\x06proto3'
)

_PERIPHERALTYPE = _descriptor.EnumDescriptor(
  name='PeripheralType',
  full_name='aranya.PeripheralType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_INVALID_PERIPHERAL_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_TYPE_NORMAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PERIPHERAL_TYPE_METRICS_REPORTER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=28,
  serialized_end=140,
)
_sym_db.RegisterEnumDescriptor(_PERIPHERALTYPE)

PeripheralType = enum_type_wrapper.EnumTypeWrapper(_PERIPHERALTYPE)
_INVALID_PERIPHERAL_TYPE = 0
PERIPHERAL_TYPE_NORMAL = 1
PERIPHERAL_TYPE_METRICS_REPORTER = 2


DESCRIPTOR.enum_types_by_name['PeripheralType'] = _PERIPHERALTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
