/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "runtime/msg_pod.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(runtime_ContainerStatus, runtime_ContainerStatus, AUTO)


PB_BIND(runtime_PodStatusMsg, runtime_PodStatusMsg, AUTO)


PB_BIND(runtime_PodStatusMsg_ContainersEntry, runtime_PodStatusMsg_ContainersEntry, AUTO)


PB_BIND(runtime_PodStatusListMsg, runtime_PodStatusListMsg, AUTO)




