# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runtime/runtime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='runtime/runtime.proto',
  package='runtime',
  syntax='proto3',
  serialized_options=b'Z+arhat.dev/aranya-proto/aranyagopb/runtimepb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15runtime/runtime.proto\x12\x07runtime\"<\n\x06Packet\x12!\n\x04kind\x18\x01 \x01(\x0e\x32\x13.runtime.PacketType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c*\xf6\x02\n\nPacketType\x12\x19\n\x15_INVALID_RUNTIME_DATA\x10\x00\x12\x10\n\x0c\x43MD_GET_INFO\x10\x01\x12\x0c\n\x08\x43MD_EXEC\x10\x02\x12\x0e\n\nCMD_ATTACH\x10\x03\x12\x0c\n\x08\x43MD_LOGS\x10\x04\x12\x12\n\x0e\x43MD_TTY_RESIZE\x10\x05\x12\x14\n\x10\x43MD_PORT_FORWARD\x10\x06\x12\r\n\tMSG_ERROR\x10\n\x12\x12\n\x0e\x43MD_IMAGE_LIST\x10\x0b\x12\x14\n\x10\x43MD_IMAGE_ENSURE\x10\x0c\x12\x14\n\x10\x43MD_IMAGE_DELETE\x10\r\x12\x14\n\x10MSG_IMAGE_STATUS\x10\x15\x12\x19\n\x15MSG_IMAGE_STATUS_LIST\x10\x16\x12\x10\n\x0c\x43MD_POD_LIST\x10\x1f\x12\x12\n\x0e\x43MD_POD_ENSURE\x10 \x12\x12\n\x0e\x43MD_POD_DELETE\x10!\x12\x12\n\x0eMSG_POD_STATUS\x10)\x12\x17\n\x13MSG_POD_STATUS_LIST\x10*B-Z+arhat.dev/aranya-proto/aranyagopb/runtimepbb\x06proto3'
)

_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='runtime.PacketType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_INVALID_RUNTIME_DATA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_GET_INFO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_EXEC', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_ATTACH', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_LOGS', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_TTY_RESIZE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_PORT_FORWARD', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSG_ERROR', index=7, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_IMAGE_LIST', index=8, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_IMAGE_ENSURE', index=9, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_IMAGE_DELETE', index=10, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSG_IMAGE_STATUS', index=11, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSG_IMAGE_STATUS_LIST', index=12, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_POD_LIST', index=13, number=31,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_POD_ENSURE', index=14, number=32,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CMD_POD_DELETE', index=15, number=33,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSG_POD_STATUS', index=16, number=41,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MSG_POD_STATUS_LIST', index=17, number=42,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=97,
  serialized_end=471,
)
_sym_db.RegisterEnumDescriptor(_PACKETTYPE)

PacketType = enum_type_wrapper.EnumTypeWrapper(_PACKETTYPE)
_INVALID_RUNTIME_DATA = 0
CMD_GET_INFO = 1
CMD_EXEC = 2
CMD_ATTACH = 3
CMD_LOGS = 4
CMD_TTY_RESIZE = 5
CMD_PORT_FORWARD = 6
MSG_ERROR = 10
CMD_IMAGE_LIST = 11
CMD_IMAGE_ENSURE = 12
CMD_IMAGE_DELETE = 13
MSG_IMAGE_STATUS = 21
MSG_IMAGE_STATUS_LIST = 22
CMD_POD_LIST = 31
CMD_POD_ENSURE = 32
CMD_POD_DELETE = 33
MSG_POD_STATUS = 41
MSG_POD_STATUS_LIST = 42



_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='runtime.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='runtime.Packet.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='runtime.Packet.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=94,
)

_PACKET.fields_by_name['kind'].enum_type = _PACKETTYPE
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.enum_types_by_name['PacketType'] = _PACKETTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), {
  'DESCRIPTOR' : _PACKET,
  '__module__' : 'runtime.runtime_pb2'
  # @@protoc_insertion_point(class_scope:runtime.Packet)
  })
_sym_db.RegisterMessage(Packet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
