/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_CMD_NODE_PB_H_INCLUDED
#define PB_ARANYA_CMD_NODE_PB_H_INCLUDED
#include <pb.h>
#include "cmd_misc.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_NodeCmd_Action {
    aranya_NodeCmd_Action__INVALID_NODE_ACTION = 0,
    aranya_NodeCmd_Action_GET_NODE_INFO_ALL = 1,
    aranya_NodeCmd_Action_GET_NODE_INFO_DYN = 2,
    aranya_NodeCmd_Action_START_NODE_SYNC_LOOP = 3
} aranya_NodeCmd_Action;

/* Struct definitions */
typedef struct _aranya_NodeCmd {
    aranya_NodeCmd_Action action;
    pb_size_t which_options;
    union {
        aranya_SyncOptions sync_options;
    } options;
} aranya_NodeCmd;


/* Helper constants for enums */
#define _aranya_NodeCmd_Action_MIN aranya_NodeCmd_Action__INVALID_NODE_ACTION
#define _aranya_NodeCmd_Action_MAX aranya_NodeCmd_Action_START_NODE_SYNC_LOOP
#define _aranya_NodeCmd_Action_ARRAYSIZE ((aranya_NodeCmd_Action)(aranya_NodeCmd_Action_START_NODE_SYNC_LOOP+1))


/* Initializer values for message structs */
#define aranya_NodeCmd_init_default              {_aranya_NodeCmd_Action_MIN, 0, {aranya_SyncOptions_init_default}}
#define aranya_NodeCmd_init_zero                 {_aranya_NodeCmd_Action_MIN, 0, {aranya_SyncOptions_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define aranya_NodeCmd_action_tag                1
#define aranya_NodeCmd_sync_options_tag          2

/* Struct field encoding specification for nanopb */
#define aranya_NodeCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,sync_options,options.sync_options),   2)
#define aranya_NodeCmd_CALLBACK NULL
#define aranya_NodeCmd_DEFAULT NULL
#define aranya_NodeCmd_options_sync_options_MSGTYPE aranya_SyncOptions

extern const pb_msgdesc_t aranya_NodeCmd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aranya_NodeCmd_fields &aranya_NodeCmd_msg

/* Maximum encoded size of messages (where known) */
#define aranya_NodeCmd_size                      15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
