/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_CMD_REJECT_PB_H_INCLUDED
#define PB_ARANYA_CMD_REJECT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_RejectCmd_Reason {
    aranya_RejectCmd_Reason__INVALID_REJECTION_REASON = 0,
    aranya_RejectCmd_Reason_REJECTION_ALREADY_CONNECTED = 1,
    aranya_RejectCmd_Reason_REJECTION_POD_STATUS_SYNC_ERROR = 2,
    aranya_RejectCmd_Reason_REJECTION_NODE_STATUS_SYNC_ERROR = 3,
    aranya_RejectCmd_Reason_REJECTION_NETWORK_UPDATE_FAILURE = 4,
    aranya_RejectCmd_Reason_REJECTION_CREDENTIAL_FAILURE = 5,
    aranya_RejectCmd_Reason_REJECTION_INTERNAL_SERVER_ERROR = 6,
    aranya_RejectCmd_Reason_REJECTION_INVALID_PROTO = 7
} aranya_RejectCmd_Reason;

/* Struct definitions */
typedef struct _aranya_RejectCmd {
    aranya_RejectCmd_Reason reason;
    pb_callback_t message;
} aranya_RejectCmd;


/* Helper constants for enums */
#define _aranya_RejectCmd_Reason_MIN aranya_RejectCmd_Reason__INVALID_REJECTION_REASON
#define _aranya_RejectCmd_Reason_MAX aranya_RejectCmd_Reason_REJECTION_INVALID_PROTO
#define _aranya_RejectCmd_Reason_ARRAYSIZE ((aranya_RejectCmd_Reason)(aranya_RejectCmd_Reason_REJECTION_INVALID_PROTO+1))


/* Initializer values for message structs */
#define aranya_RejectCmd_init_default            {_aranya_RejectCmd_Reason_MIN, {{NULL}, NULL}}
#define aranya_RejectCmd_init_zero               {_aranya_RejectCmd_Reason_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define aranya_RejectCmd_reason_tag              1
#define aranya_RejectCmd_message_tag             2

/* Struct field encoding specification for nanopb */
#define aranya_RejectCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define aranya_RejectCmd_CALLBACK pb_default_field_callback
#define aranya_RejectCmd_DEFAULT NULL

extern const pb_msgdesc_t aranya_RejectCmd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aranya_RejectCmd_fields &aranya_RejectCmd_msg

/* Maximum encoded size of messages (where known) */
/* aranya_RejectCmd_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
