/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_CMD_STORAGE_PB_H_INCLUDED
#define PB_ARANYA_CMD_STORAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_StorageCmd_Action {
    aranya_StorageCmd_Action__INVALID_STORAGE_ACTION = 0,
    aranya_StorageCmd_Action_MOUNT_REMOTE_VOLUME = 1,
    aranya_StorageCmd_Action_UNMOUNT_REMOTE_VOLUME = 2
} aranya_StorageCmd_Action;

/* Struct definitions */
typedef struct _aranya_RemoteVolumeMountOptions {
    pb_callback_t remote_path;
    pb_callback_t local_path;
} aranya_RemoteVolumeMountOptions;

typedef struct _aranya_StorageCmd {
    aranya_StorageCmd_Action action;
    pb_size_t which_options;
    union {
        aranya_RemoteVolumeMountOptions mount;
    } options;
} aranya_StorageCmd;


/* Helper constants for enums */
#define _aranya_StorageCmd_Action_MIN aranya_StorageCmd_Action__INVALID_STORAGE_ACTION
#define _aranya_StorageCmd_Action_MAX aranya_StorageCmd_Action_UNMOUNT_REMOTE_VOLUME
#define _aranya_StorageCmd_Action_ARRAYSIZE ((aranya_StorageCmd_Action)(aranya_StorageCmd_Action_UNMOUNT_REMOTE_VOLUME+1))


/* Initializer values for message structs */
#define aranya_StorageCmd_init_default           {_aranya_StorageCmd_Action_MIN, 0, {aranya_RemoteVolumeMountOptions_init_default}}
#define aranya_RemoteVolumeMountOptions_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define aranya_StorageCmd_init_zero              {_aranya_StorageCmd_Action_MIN, 0, {aranya_RemoteVolumeMountOptions_init_zero}}
#define aranya_RemoteVolumeMountOptions_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define aranya_RemoteVolumeMountOptions_remote_path_tag 1
#define aranya_RemoteVolumeMountOptions_local_path_tag 2
#define aranya_StorageCmd_action_tag             1
#define aranya_StorageCmd_mount_tag              2

/* Struct field encoding specification for nanopb */
#define aranya_StorageCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,mount,options.mount),   2)
#define aranya_StorageCmd_CALLBACK NULL
#define aranya_StorageCmd_DEFAULT NULL
#define aranya_StorageCmd_options_mount_MSGTYPE aranya_RemoteVolumeMountOptions

#define aranya_RemoteVolumeMountOptions_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_path,       1) \
X(a, CALLBACK, SINGULAR, STRING,   local_path,        2)
#define aranya_RemoteVolumeMountOptions_CALLBACK pb_default_field_callback
#define aranya_RemoteVolumeMountOptions_DEFAULT NULL

extern const pb_msgdesc_t aranya_StorageCmd_msg;
extern const pb_msgdesc_t aranya_RemoteVolumeMountOptions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aranya_StorageCmd_fields &aranya_StorageCmd_msg
#define aranya_RemoteVolumeMountOptions_fields &aranya_RemoteVolumeMountOptions_msg

/* Maximum encoded size of messages (where known) */
/* aranya_StorageCmd_size depends on runtime parameters */
/* aranya_RemoteVolumeMountOptions_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
