/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARANYA_CMD_CREDENTIAL_PB_H_INCLUDED
#define PB_ARANYA_CMD_CREDENTIAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _aranya_CredentialCmd_Action {
    aranya_CredentialCmd_Action__INVALID_CREDENTIAL_ACTION = 0,
    aranya_CredentialCmd_Action_UPDATE_STORAGE_CREDENTIAL = 1
} aranya_CredentialCmd_Action;

/* Struct definitions */
typedef struct _aranya_StorageCredentialOptions {
    pb_callback_t ssh_private_key;
} aranya_StorageCredentialOptions;

typedef struct _aranya_CredentialCmd {
    aranya_CredentialCmd_Action action;
    pb_size_t which_options;
    union {
        aranya_StorageCredentialOptions storage;
    } options;
} aranya_CredentialCmd;


/* Helper constants for enums */
#define _aranya_CredentialCmd_Action_MIN aranya_CredentialCmd_Action__INVALID_CREDENTIAL_ACTION
#define _aranya_CredentialCmd_Action_MAX aranya_CredentialCmd_Action_UPDATE_STORAGE_CREDENTIAL
#define _aranya_CredentialCmd_Action_ARRAYSIZE ((aranya_CredentialCmd_Action)(aranya_CredentialCmd_Action_UPDATE_STORAGE_CREDENTIAL+1))


/* Initializer values for message structs */
#define aranya_CredentialCmd_init_default        {_aranya_CredentialCmd_Action_MIN, 0, {aranya_StorageCredentialOptions_init_default}}
#define aranya_StorageCredentialOptions_init_default {{{NULL}, NULL}}
#define aranya_CredentialCmd_init_zero           {_aranya_CredentialCmd_Action_MIN, 0, {aranya_StorageCredentialOptions_init_zero}}
#define aranya_StorageCredentialOptions_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define aranya_StorageCredentialOptions_ssh_private_key_tag 1
#define aranya_CredentialCmd_action_tag          1
#define aranya_CredentialCmd_storage_tag         2

/* Struct field encoding specification for nanopb */
#define aranya_CredentialCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (options,storage,options.storage),   2)
#define aranya_CredentialCmd_CALLBACK NULL
#define aranya_CredentialCmd_DEFAULT NULL
#define aranya_CredentialCmd_options_storage_MSGTYPE aranya_StorageCredentialOptions

#define aranya_StorageCredentialOptions_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    ssh_private_key,   1)
#define aranya_StorageCredentialOptions_CALLBACK pb_default_field_callback
#define aranya_StorageCredentialOptions_DEFAULT NULL

extern const pb_msgdesc_t aranya_CredentialCmd_msg;
extern const pb_msgdesc_t aranya_StorageCredentialOptions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aranya_CredentialCmd_fields &aranya_CredentialCmd_msg
#define aranya_StorageCredentialOptions_fields &aranya_StorageCredentialOptions_msg

/* Maximum encoded size of messages (where known) */
/* aranya_CredentialCmd_size depends on runtime parameters */
/* aranya_StorageCredentialOptions_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
