/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "msg_pod.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aranya_PodStatus, aranya_PodStatus, AUTO)


PB_BIND(aranya_PodStatus_ContainerStatus, aranya_PodStatus_ContainerStatus, AUTO)


PB_BIND(aranya_PodStatus_ContainerStatusesEntry, aranya_PodStatus_ContainerStatusesEntry, AUTO)


PB_BIND(aranya_PodStatusList, aranya_PodStatusList, AUTO)


PB_BIND(aranya_Image, aranya_Image, AUTO)


PB_BIND(aranya_ImageList, aranya_ImageList, AUTO)




